### PR TITLE
Merge Collection Extensions feature into master

### PR DESCRIPTION
**Pull request by elrayle**
This feature branch brings in extensions to collections which includes...
* collection types
* nesting of collections of the same type
* branding including banner and logo images
* control of discovery options
* control of multiple membership
* extended sharing allowing permissions for other users/groups to be granted on the collection and optionally on works created in the collection

@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by mcwhitaker** [comment]
I agree with the approach proposed by @jeremyf . Indiana University has committed QA resources to the testing effort and we will study our options with respect to developer time. We will come back here early next week with our conclusions about how much developer help we can offer.

**Comment by jeremyf** [comment]
Thank you @mcwhitaker for your response. I didn't know how to consider the QA effort; I know bug fixing effort and QA go hand in hand.

**Comment by elrayle** [comment]
@mcwhitaker I am glad to here that Indiana will be part of the release process.  A good place to identify resources available for QA and Bug Fixing is on the wiki page [Collection Extensions - QA and Release](https://wiki.duraspace.org/x/bjNsBQ), which now that I think of it should probably be renamed Hyrax 2.1 - QA and Release.

**Comment by mcwhitaker** [comment]
@elrayle I included our QA analyst name on that list earlier this week. When we know about developer availability, I will add it there. Thank you.

**Pull request merged**
