### PR TITLE
1.0-stable encoding fix

### PR DESCRIPTION
**Pull request by dheles**
Backports the fix for encoding issues from 2.x to 1.0 stable

@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by jcoyne** [comment]
I'm curious as to why the second commit isn't a cherry-pick of https://github.com/samvera/hyrax/commit/e0b5359c23ec46706132e55bcffa3af25d698a13 @dheles Can you explain?

**Comment by dheles** [comment]
@jcoyne no reason other than that I had seen the result (adding "Hyrax::Engine.root" to the filename path) and the need, but had not noted the commit as a discrete and cherry-pick-able one we could use here. i'm happy to make changes, if that would be preferable.

**Comment by jcoyne** [comment]
@dheles I recommend we do that as it's a little easier to diff the two branches that way.

**Comment by dheles** [comment]
yikes! been sleeping on this... the CLAs are in, can we get this merged, plz?

**Comment by mjgiarlo** [comment]
@dheles Got it! And @hortongn's 8th backport as well.

**Comment by dheles** [comment]
woot! much obliged, @mjgiarlo

**Pull request merged**
