### PR TITLE
Replace hard-coded strings in erb  i18n

### PR DESCRIPTION
**Pull request by jmfrenzel**
Fixes #issuenumber ; refs #issuenumber

This PR replaces hard-coded strings in views (*.erb) and adds i18n translation 

The following files are not included in the PR, but have hard-coded strings:
* app/views/hyrax/content_blocks/templates/agreement.html.erb
* app/views/hyrax/content_blocks/templates/terms.html.erb
* app/views/hyrax/operations/show.html.erb

The following files have been semi-(manually) checked: 

```bash
grep -r -n "h1\|\h2\|h3\|h4\|<label\|submit\|<th\|legend\|btn" app/views/hyrax/ |grep -v "t(:\|thead\|admin\|each_with" | sed -r 's/\:/ /' |awk '{print $1}' |sort -u |grep -v "app/views/hyrax/transfers/_received.html.erb\|app/views/hyrax/transfers/_sent.html.erb\|app/views/hyrax/dashboard/profiles/_edit_primary.html.erb\|app/views/hyrax/base/_attributes.html.erb\|app/views/hyrax/base/_citations.html.erb\|app/views/hyrax/base/edit.html.erb\|app/views/hyrax/base/_file_manager_actions.html.erb\|app/views/hyrax/base/file_manager.html.erb\|app/views/hyrax/base/_form_child_work_relationships.html.erb\|app/views/hyrax/base/_form_files.html.erb\|app/views/hyrax/base/_form_member_of_collections.html.erb\|app/views/hyrax/base/_form_metadata.html.erb\|app/views/hyrax/base/_form_permission.html.erb\|app/views/hyrax/base/_form_permission_under_embargo.html.erb\|app/views/hyrax/base/_form_permission_under_lease.html.erb\|app/views/hyrax/base/_form_progress.html.erb\|app/views/hyrax/base/_form_relationships.html.erb\|app/views/hyrax/base/_form_rendering.html.erb\|app/views/hyrax/base/_form_representative.html.erb\|app/views/hyrax/base/_form_share.html.erb\|app/views/hyrax/base/_form_thumbnail.html.erb\|app/views/hyrax/base/_form_visibility_component.html.erb\|app/views/hyrax/base/_items.html.erb\|app/views/hyrax/base/new.html.erb\|app/views/hyrax/base/_show_actions.html.erb\|app/views/hyrax/base/show.html.erb\|app/views/hyrax/base/_social_media.html.erb\|app/views/hyrax/base/unavailable.html.erb\|app/views/hyrax/base/_work_title.erb\|app/views/hyrax/batch_edits/_check_all.html.erb\|app/views/hyrax/collections/_bookmark_control.html.erb\|app/views/hyrax/collections/_collection_title.erb\|app/views/hyrax/collections/_default_group.html.erb\|app/views/hyrax/collections/_list_works.html.erb\|app/views/hyrax/collections/_search_form.html.erb\|app/views/hyrax/collections/_search_results.html.erb\|app/views/hyrax/collections/show.html.erb\|app/views/hyrax/collections/_view_type_group.html.erb\|app/views/hyrax/contact_form/create.html.erb\|app/views/hyrax/contact_form/new.html.erb\|app/views/hyrax/content_blocks/_form.html.erb\|app/views/hyrax/dashboard/collections/_bookmark_control.html.erb\|app/views/hyrax/dashboard/collections/_button_create_collection.html.erb\|app/views/hyrax/dashboard/collections/_button_for_batch_delete_collection.html.erb\|app/views/hyrax/dashboard/collections/_button_for_remove_selected_from_collection.html.erb\|app/views/hyrax/dashboard/collections/_button_for_update_collection.html.erb\|app/views/hyrax/dashboard/collections/_button_remove_from_collection.html.erb\|app/views/hyrax/dashboard/collections/_collection_title.html.erb\|app/views/hyrax/dashboard/collections/_default_group.html.erb\|app/views/hyrax/dashboard/collections/_edit_actions.html.erb\|app/views/hyrax/dashboard/collections/edit.html.erb\|app/views/hyrax/dashboard/collections/_form_branding.html.erb\|app/views/hyrax/dashboard/collections/_form_discovery.html.erb\|app/views/hyrax/dashboard/collections/_form_for_select_collection.html.erb|\app/views/hyrax/dashboard/collections/_form.html.erb\|app/views/hyrax/dashboard/collections/_form_for_select_collection.html.erb\|app/views/hyrax/dashboard/collections/_form.html.erb\|app/views/hyrax/dashboard/collections/_form_share.html.erb\|app/views/hyrax/dashboard/collections/_form_share_table.html.erb\|app/views/hyrax/dashboard/collections/_list_works.html.erb\|app/views/hyrax/dashboard/collections/_modal_parent_collection_remove_deny.html.erb\|app/views/hyrax/dashboard/collections/_modal_remove_from_collection.html.erb\|app/views/hyrax/dashboard/collections/_modal_remove_sub_collection.html.erb\|app/views/hyrax/dashboard/collections/new.html.erb\|app/views/hyrax/dashboard/collections/_show_actions.html.erb\|app/views/hyrax/dashboard/collections/_show_add_items_actions.html.erb\|app/views/hyrax/dashboard/collections/_show_descriptions.html.erb\|app/views/hyrax/dashboard/collections/show.html.erb\|app/views/hyrax/dashboard/collections/_show_parent_collection_row.html.erb\|app/views/hyrax/dashboard/collections/_show_subcollection_actions.html.erb\|app/views/hyrax/dashboard/collections/_sort_and_per_page.html.erb\|app/views/hyrax/dashboard/collections/_subcollection_list.html.erb\|app/views/hyrax/dashboard/_index_partials/_proxy_rights.html.erb\|app/views/hyrax/dashboard/_index_partials/_transfers.html.erb\|app/views/hyrax/dashboard/profiles/edit.html.erb\|app/views/hyrax/dashboard/profiles/show.html.erb\|app/views/hyrax/dashboard/profiles/_trophy_edit.html.erb\|app/views/hyrax/dashboard/profiles/_zotero.html.erb\|app/views/hyrax/dashboard/_repository_growth.html.erb\|app/views/hyrax/dashboard/_repository_objects.html.erb\|app/views/hyrax/dashboard/show_user.html.erb\|app/views/hyrax/dashboard/_user_activity.html.erb\|app/views/hyrax/dashboard/works/_default_group.html.erb\|app/views/hyrax/dashboard/works/_list_works.html.erb\|app/views/hyrax/depositors/index.html.erb\|app/views/hyrax/embargoes/edit.html.erb\|app/views/hyrax/embargoes/index.html.erb\|app/views/hyrax/embargoes/_table_headers.html.erb\|app/views/hyrax/file_sets/edit.html.erb\|app/views/hyrax/file_sets/_file_set_title.erb\|app/views/hyrax/file_sets/_form.html.erb\|app/views/hyrax/file_sets/media_display/_image.html.erb\|app/views/hyrax/file_sets/media_display/_image.html.erb\|app/views/hyrax/file_sets/media_display/_office_document.html.erb\|app/views/hyrax/file_sets/media_display/_pdf.html.erb\|app/views/hyrax/file_sets/_permission.html.erb\|app/views/hyrax/file_sets/_show_actions.html.erb\|app/views/hyrax/file_sets/_show_details.html.erb\|app/views/hyrax/file_sets/_single_use_link_rows.html.erb\|app/views/hyrax/file_sets/_single_use_links.html.erb\|app/views/hyrax/homepage/_explore_collections.html.erb\|app/views/hyrax/homepage/_featured_fields.html.erb\|app/views/hyrax/homepage/_featured_works.html.erb\|app/views/hyrax/homepage/_home_content.html.erb\|app/views/hyrax/homepage/index.html.erb\|app/views/hyrax/homepage/_recent_document.html.erb\|app/views/hyrax/homepage/_recently_uploaded.html.erb\|app/views/hyrax/homepage/_sortable_featured.html.erb\|app/views/hyrax/leases/edit.html.erb\|app/views/hyrax/leases/index.html.erb\|app/views/hyrax/leases/_list_expired_active_leases.html.erb\|app/views/hyrax/leases/_table_headers.html.erb\|app/views/hyrax/my/_collection_action_menu.html.erb\|app/views/hyrax/my/collections/_batch_actions.html.erb\|app/views/hyrax/my/collections/_default_group.html.erb\|app/views/hyrax/my/collections/_list_collections.html.erb\|app/views/hyrax/my/collections/_modal_add_subcollection.html.erb\|app/views/hyrax/my/collections/_modal_add_to_collection_deny.html.erb\|app/views/hyrax/my/collections/_modal_add_to_collection.html.erb\|app/views/hyrax/my/collections/_modal_add_to_collection_permission_deny.html.erb\|app/views/hyrax/my/collections/_modal_collection_types_to_create.html.erb\|app/views/hyrax/my/collections/_modal_delete_collection_deny.html.erb\|app/views/hyrax/my/collections/_modal_delete_collection.html.erb\|app/views/hyrax/my/collections/_modal_delete_collections_deny.html.erb\|app/views/hyrax/my/collections/_modal_delete_deny.html.erb\|app/views/hyrax/my/collections/_modal_delete_empty_collection.html.erb\|app/views/hyrax/my/collections/_modal_delete_selected_collections.html.erb\|app/views/hyrax/my/collections/_modal_edit_deny.html.erb\|app/views/hyrax/my/_constraints.html.erb\|app/views/hyrax/my/_did_you_mean.html.erb\|app/views/hyrax/my/facet.html.erb\|app/views/hyrax/my/_facet_layout.html.erb\|app/views/hyrax/my/_facet_pagination.html.erb\|app/views/hyrax/my/_search_form.html.erb\|app/views/hyrax/my/_work_action_menu.html.erb\|app/views/hyrax/my/works/_batch_actions.html.erb\|app/views/hyrax/my/works/_default_group.html.erb\|app/views/hyrax/my/works/_list_works.html.erb\|app/views/hyrax/notifications/_notifications.html.erb\|app/views/hyrax/pages/_form.html.erb\|app/views/hyrax/permissions/confirm_access.html.erb\|app/views/hyrax/permissions/confirm.html.erb\|app/views/hyrax/single_use_links_viewer/show.html.erb\|app/views/hyrax/stats/file.html.erb\|app/views/hyrax/stats/work.html.erb\|app/views/hyrax/transfers/index.html.erb\app/views/hyrax/transfers/new.html.erb\|app/views/hyrax/transfers/index.html.erb\|app/views/hyrax/transfers/new.html.erb\|app/views/hyrax/users/_user.html.erb\|app/views/hyrax/users/_search_form.html.erb\|app/views/hyrax/users/_proxies.html.erb\|app/views/hyrax/users/_left_sidebar.html.erb\|app/views/hyrax/users/index.html.erb\|app/views/hyrax/my/works/index.html.erb\|app/views/hyrax/my/index.html.erb\|app/views/hyrax/my/collections/index.html.erb\|app/views/hyrax/my/_sort_and_per_page.html.erb\|app/views/hyrax/collections/_show_document_list.html.erb\|app/views/hyrax/collections/_sort_and_per_page.html.erb\|app/views/hyrax/batch_edits/_delete_selected.html.erb\|app/views/hyrax/base/_work_button_row.html.erb\|app/views/hyrax/file_sets/_actions.html.erb\|app/views/hyrax/file_sets/_descriptions.html.erb\|app/views/hyrax/file_sets/_extra_fields_modal.html.erb\|app/views/hyrax/file_sets/_permission_form.html.erb\|app/views/hyrax/file_sets/_versioning.html.erb\|app/views/hyrax/file_sets/proxy.html.erb\|app/views/hyrax/embargoes/_list_expired_active_embargoes.html.erb\|app/views/hyrax/notifications/index.html.erb\|app/views/hyrax/uploads/_js_templates.html.erb\|app/views/hyrax/operations/index.html.erb\|app/views/hyrax/uploads/_js_templates_branding.html.erb\|app/views/hyrax/batch_edits/edit.html.erb\|app/views/hyrax/dashboard/collections/_show_document_list.html.erb\|app/views/hyrax/dashboard/collections/_show_document_list_menu.html.erb\|app/views/hyrax/dashboard/collections/_show_document_list_row.html.erb\|app/views/hyrax/dashboard/collections/_work_action_menu.html.erb\|app/views/hyrax/base/unauthorized.html.erb\|app/views/hyrax/base/inspect_work.html.erb\|app/views/hyrax/citations/work.html.erb\|app/views/hyrax/users/_activity_log.html.erb\|app/views/hyrax/single_use_links_viewer/single_use_error.html.erb\|app/views/hyrax/file_sets/media_display/_audio.html.erb\|app/views/hyrax/file_sets/media_display/_video.html.erb\|app/views/hyrax/base/_workflow_actions.html.erb\|app/views/hyrax/static/mendeley.html.erb\|app/views/hyrax/static/zotero.html.erb"
```
@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by no-reply** [comment]
I'm pulling this to run i18n, and will mark it ready for review when i've pushed those changes.

**Comment by cjcolvar** [comment]
@jmfrenzel It looks like there are a few failing tests coming from one translation missing:
`translation missing: en.hyrax.base.form_permission.visibility`

**Comment by cjcolvar** [comment]
@jmfrenzel Thanks for following up to fix that.  Do you mind making this PR no longer a draft by marking this ready for review if you think it is ready?

**Comment by jmfrenzel** [comment]
@cjcolvar marked it for ready, however :point_up: @no-reply wants to run i18n before merging  https://github.com/samvera/hyrax/pull/3898#issuecomment-514844666

**Comment by Dananji** [comment]
This looks good :+1: 
There are still some places with the hard-coded values instead i18n translations. Couple of places I found were;
1. https://github.com/samvera/hyrax/blob/master/app/views/catalog/_index_list_default.html.erb#L19 & L22
2. Placeholder texts for dropdown and text fields: https://github.com/samvera/hyrax/blob/master/app/views/hyrax/admin/admin_sets/_form_participants.html.erb#L19 
3. Table definition: https://github.com/samvera/hyrax/blob/master/app/views/hyrax/admin/admin_sets/index.html.erb#L19
4. https://github.com/samvera/hyrax/blob/master/app/views/hyrax/users/_user_info.html.erb#L14 and text interpretations for the other handles

Because the hard-coded strings were replaced by i18n translation values for English language, and they were not added to the other languages some pages throw errors (e.g.: `translation missing: es.hyrax.my.count.collections.collections_listing`) when language is changed. I think this is future work based on this work.

**Comment by cjcolvar** [comment]
@Dananji I talked with @no-reply and he will generate the other languages after this PR is merged so I wouldn't worry about those missing keys yet.  
As for the other hard-coded strings, maybe those could be covered in a separate smaller PR so this one could go ahead be merged.  So if the PR looks good to you as it is now do you mind approving?

**Pull request merged**
