### PR TITLE
[WIP] Remove Solr suggest fields because of @awead's presentation at …

### PR DESCRIPTION
**Pull request by mjgiarlo**
…SC2017, to see if 1) anything breaks, and 2) the test suite's performance is affected

### CODE REVIEW

**Comment by jcoyne** [comment]
@awead does suggest power the Blacklight autocomplete functionality?

**Comment by awead** [comment]
@jcoyne not sure. I didn't really investigate any further, other than noting that indexing performance improved when we disabled these fields. It be worth finding out if there's something in the `suggest` field configuration that's causing the problem, instead of disabling it entirely.

**Comment by mjgiarlo** [comment]
@jcoyne does that work in Hyrax?

**Comment by jcoyne** [comment]
@mjgiarlo it does, but it's not turned on in our default templates.

**Pull request closed without merging**
