### PR TITLE
Allow i18n via data properties like on all the other fields.

### LINKED ISSUE #3461: "Based near" field does not allow internationalization of "add" and "remove" buttons labels
### Descriptive summary

The "based near" field does not take into account the customization of the text of the add / remove buttons via the data attributes (Hyrax 3.0.0 pre beta 1)

### Rationale
All multivalued fields in Hyrax can have the labels of their "add" and "remove" buttons modified by data attributes in erb template.

```
wrapper_html: {
    #...
    data:
        {"add-text": t("my_key_for_add"),"remove-text": t("my_key_for_remove")
    }
},
```
This attributes are merged into default options in hydra-editor's manage_repeating_fields.js
`var options = $.extend({}, DEFAULTS, $this.data(), typeof option == 'object' && option);`
But based near does not take them into account.

### Expected behavior

A custom text appears on the "add" and "remove" buttons of the based near field, possibly allowing internationalization.

### Actual behavior

The default strings that are in English in the code of controlled_vocabulary.es6 cant be changed ( ["Add another"](https://github.com/samvera/hyrax/blob/9c69ac45c17b5b6b28e08dbc2dd31b42dcb349aa/app/assets/javascripts/hyrax/editor/controlled_vocabulary.es6#L23) and ["Remove"](https://github.com/samvera/hyrax/blob/9c69ac45c17b5b6b28e08dbc2dd31b42dcb349aa/app/assets/javascripts/hyrax/editor/controlled_vocabulary.es6#L26) )

### Steps to reproduce the behavior

1. Copy based_near.html.erb to your app/views/records/edit_fields directory
2. Modify the wrapper_html/data key :
```
wrapper_html: {
    data: {
        'autocomplete-url' => "/authorities/search/geonames",
        'field-name' => key,
        "add-text": "My text",
        "remove-text": "My other text"
    }
},
```

3. Nothing happens
Whereas if you do the same manipulation on another multivalued field, it works.

### Suggested solution

You should probably replace [this line](https://github.com/samvera/hyrax/blob/9c69ac45c17b5b6b28e08dbc2dd31b42dcb349aa/app/assets/javascripts/hyrax/editor/controlled_vocabulary.es6#L30) in controlled_vocabulary.es6
```
 super(element, options)
```
by :
```
super(element, $.extend({}, options, $(element).data()));
```

### PR DESCRIPTION
**Pull request by j-dornbusch**
Fixes #3461

Allow i18n via data properties, like on all the other fields.

On all fields except "location" (based_near), the "add another" button can be internationalized by data properties.

``` ruby
data: { 'autocomplete-url' => "/authorities/search/geonames",
                                    'field-name' => key,
                                    "add-text": t(".add_another"),
                                    "remove-text":  t(".remove")}
```
This attributes are merged into default options in hydra-editor's manage_repeating_fields.js
`var options = $.extend({}, DEFAULTS, $this.data(), typeof option == 'object' && option);`
But based near does not take them into account.

Changes proposed in this pull request:

You can override default options in ControlledVocabulary like in hydra-editor's manage_repeating_fields.js.

Guidance for testing, such as acceptance criteria or new user interface behaviors:

* customize 'add text' and 'remove text' in app/views/records/edit_fields/_based_near.html.erb
```ruby
data:
    {
     "add-text": t("my_key_for_add"),"remove-text": t("my_key_for_remove")
    }
```
* Observe the result in the form label

@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by cjcolvar** [comment]
@adamjarling What are your thoughts on this PR?  Is the use of jquery an issue?

**Comment by j-dornbusch** [comment]
@j-dornbusch After rebasing, all tests pass on circleci.
@adamjarling  This line of jquery is required for a consistent approach of the client-side i18n  with hydra editor : https://github.com/samvera/hydra-editor/blob/9aa84288a10aa228ddda0388fdca90240178ccba/app/assets/javascripts/hydra-editor/manage_repeating_fields.js#L32

**Comment by adamjarling** [comment]
@j-dornbusch @cjcolvar Yea, this looks good to me.

**Comment by cjcolvar** [comment]
It looks like the rebase brought in unrelated changes that should already be in master.  I think this PR will be ready once those are removed.

**Comment by no-reply** [comment]
Since this was stalled pending removal of some unwanted changes, I opened an new PR (#3564) with just the relevant change.

Thanks @j-dornbusch!

**Comment by j-dornbusch** [comment]
@no-reply Thank you for handling the problem.

**Pull request closed without merging**
