### PR TITLE
Removes FileSet related objects when work deleted (#6334).

### LINKED ISSUE #6334: In valkyrie/fedora deleting a work leaves orphan FileMetadata objects
### Descriptive summary

In valkyrie/fedora deleting a work leaves orphan FileMetadata objects

### Steps to reproduce the behavior in User Interface (UI)

1. Load sirenia (#6331)
2. Create a monograph
3. Delete the monograph (may produce error, see #6333)
4. Observe FileMetadata objects in fedora and solr

### Actual behavior (include screenshots if available)

FileMetadata objects left in fedora and solr after their associated objects were deleted

### Acceptance Criteria/Expected Behavior

- [ ] FileMetadata objects are deleted when their parent FileSet is deleted

### Related work

#6331

### PR DESCRIPTION
**Pull request by bwatson78**
### Fixes

Fixes #6334 

### Summary

Adds transaction triggers that removes FileSets' Hyrax::FileMetadata and AccessControl objects.

### Guidance for testing, such as acceptance criteria or new user interface behaviors:
* Load sirenia (https://github.com/samvera/hyrax/pull/6331)
* Open http://localhost:8081/fcrepo/rest/development and take note of number of objects present (clean install should have 2)
* Create monograph and reload the Fedora UI above. Take note of added number of objects (usually 6)
* Delete the monograph
* Reload the Fedora UI once more. The object total should return to the original number

### Type of change (for release notes)

`notes-valkyrie` Valkyrie Progress

### Detailed Description

Adds transaction triggers that removes FileSets' Hyrax::FileMetadata and AccessControl objects.

### Changes proposed in this pull request:
* Override lib/hyrax/transactions/work_destroy.rb's #call to process private methods that find the Work's associated FileSets and remove the previously orphaned Hyrax::FileMetadata and AccessControl objects tie to them.

@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by dlpierce** [comment]
The pattern for transactions/steps has been to put all of the actual work in a step and keep transactions contain only a list of steps to take, so this should be moved to a step.

I wonder if UpdateWorkMembers could be of use?

**Comment by bwatson78** [comment]
@dlpierce I've added my best attempt of rspec here. I tried to get a work with a fileset that contained a file with an associated FileMetadata object, but I couldn't get one going.

**Comment by dlpierce** [comment]
I tried this out on clean koppie and sirenia.

- I created a generic work with one file. 
- Sirenia: Everything related to the work is cleared from fedora, although solr still has records for two FileMetadata objects.
- Koppie: Postgres still contains one FileSet object, solr has records for two FileMetadata objects and one FileSet

It looks like the steps do not actually remove the FileSet as it is now, so I'm curious how it was removed from Fedora

**Comment by bwatson78** [comment]
I forgot to check Koppie--apologies for that. When we last discussed the work deletion behavior, I commented how it appears the object created by the `resource_factory` that is sent to Fedora to delete the work included references to the associated FileSet. Looking for that now...

**Comment by bwatson78** [comment]
For the Solr objects--should I just kick off a full reindex?

**Comment by bwatson78** [comment]
Should I reverse tactics and experiment with explictly deleting all FileSets attached to a Work before deleting the Work itself? See if that takes care of all of the FileSets' children without having to call all of the other steps?

**Comment by dlpierce** [comment]
The deletion dependency seems possible. The way I see it working is the destroy work steps should include a call to a step to destroy the FileSet, which then destroys its FileMetadata objects. I think the generic delete resource step can be used at each level to carry out the actual deletion? That way the number of places in code concerned with doing a given action is kept to a minimum.

**Comment by bwatson78** [comment]
Alrighty, I'll see how making a call to delete all FileSets before deleting the Work goes.

**Comment by bwatson78** [comment]
@dlpierce When attempting to call the `Hyrax::Transactions::Container['file_set.destroy']` from within the same step I've been working on, I received an LDP::Gone error from this file: app/services/hyrax/listeners/member_cleanup_listener.rb. I realized that the transaction wasn't set up there, like it should be. That's why we still have orphans (and why `work_resource.destroy` deletes the FileSet--that is, at least for Fedora. I don't know why this doesn't work for PG yet.)

This "fix" doesn't fix everything, though. An ACL for the FileSet is still left behind. And, for some reason, Solr is left with the AdminSet and 2 FileMetadata objects (which are gone from Fedora.) I think I'll add a full reindex call into the same method I've already altered.

**Comment by bwatson78** [comment]
@dlpierce I've removed all of the errant objects (Solr and Fedora) on the Sirenia side. I've run out of time for today, so I couldn't get to Koppie testing or rspec. See you on Monday the 16th.

**Comment by bwatson78** [comment]
This should be ready for review. The Koppie side of thing is affected by the Work being removed before queried for its child members.

**Review by dlpierce — APPROVED** [review]

**Pull request merged**
