### PR TITLE
Delete unused _user_util_links_extra.html.erb

### PR DESCRIPTION
**Pull request by bbpennel**
### Fixes

No tickets

### Summary

Deletes an unused empty file:
https://github.com/samvera/hyrax/blob/main/app/views/hyrax/users/_user_util_links_extra.html.erb

### Type of change (for release notes)

Should be no functional changes

### Detailed Description

I encountered this file while updating our local overrides of user_util_links.html.erb, and initially wondered if it was an empty template for adding additional links to the header (which might be nice to have). Adding contents to it had no affect, and as Jeremy Friesen noted, there are no references to the file in any hyrax/hyku/samvera projects, and no other instances of the file. Its been around since the sufia days, so it is most likely defunct and can be removed.

### Changes proposed in this pull request:
* Deleting _user_util_links_extra.html.erb

@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by jeremyf** [comment]
Building support for this PR, I wrote the following in Slack:

> I have a large number of hyrax/hyku files on my machine.  The only instance of the `_user_util_links_extra.html.erb` is in Hyrax. And there are no references `user_util_links_extra` in all of my git repos.
>
> Thinking that maybe devise scope matters (e.g. :user ), I further checked for `util_links_extra` and found nothing.
>
> Now, there is an abundance of render partial: `user_util_links` so I’m guessing it’s a vestigial thing

**Review by jeremyf — APPROVED** [review]

**Comment by dlpierce** [comment]
@bbpennel If you rebase this I think the specs should be able to run now.

**Comment by bbpennel** [comment]
@dlpierce Rebased, but still failing on "build and push image" 😢

**Comment by dlpierce** [comment]
Sorry, we cannot run CI on forked PRs, at least for the time being. I'll recreate this in the hyrax repo.

**Comment by bbpennel** [comment]
Looks like I have permission to push branches to the main hyrax repo now, so I'll do that in the future instead of using our local fork.

**Pull request closed without merging**
