### PR TITLE
a first hack at editing admin sets using Valkyrie

### PR DESCRIPTION
**Pull request by no-reply**
working on a transactional approach
@samvera/hyrax-code-reviewers

### CODE REVIEW

**Review by elrayle — COMMENTED** [review]
I fixed the rubocop errors.  Tests pass.  Is there anything else making this a draft?  It all looks good to me.

**Comment by no-reply** [comment]
i think this could still use a little more attention, but i don't see any reason not to merge it until then.

**Comment by no-reply** [comment]
@elrayle it seems like you are also doing this, but i've been testing this by switching the controller's `load_and_authorize_resource` arguments to include `class: 'Hyrax::AdministrativeSet'`. at that point, the existing tests seem solid for testing Valkyrie handling.

**Review by elrayle — APPROVED** [review]
Looks great.  This really moves admin sets along.

**Pull request merged**
