### PR TITLE
branding a collection

### PR DESCRIPTION
**Pull request by blancoj**
@elrayle here is the collection branding pr addressing issue #1376

### CODE REVIEW

**Comment by elrayle** [comment]
@mjgiarlo So how rigid is our compliance with hound?  If I follow hounds suggestions 'Avoid qualifying class selectors with an element' the UI styles break.

Otherwise, ready for review and merge.

**Comment by elrayle** [comment]
There is 1 failing test that is the known randomly failing batch_edit test.

@jeremyf This PR is ready for review and merge.  Do you have a minute to review?

**Comment by jeremyf** [comment]
Note. This is failing with a known (and erratic) failure.

**Comment by jeremyf** [comment]
@blancoj This PR is missing tests for both the controller and the model. Can you write up expectations in Rspec (even if you don't write the specs themselves)? 

I'm thinking along the lines of:

```ruby
RSpec.describe do
  describe 'GET #show' do
    it 'will assign @banner_file if banner info exists'
  end
end
```

There are some significant code changes that are introduced and we need to automate their expectations.

**Comment by elrayle** [comment]
There is 1 failing test that is the known randomly failing batch_edit test.

**Pull request merged**
