### PR TITLE
Don't set theme to a layout.

### LINKED ISSUE #2126: Theme is set to a layout, not a theme
https://github.com/samvera/hyrax/pull/1866/files#diff-a726cb6c8d865da58ddb08a5f7b10fccR15

`hyrax` is a theme. but `hyrax/1_column` is a layout, and you should not be a valid theme.

### PR DESCRIPTION
**Pull request by jcoyne**
The theme contains many layouts and is set in ApplicationController.

Fixes #2126

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@jcoyne can you take screenshots of the work and collection show views to confirm the navbars are still present?

**Comment by no-reply** [comment]
Failure is due to network disconnect between CI and `svn.apache.org`. I'm restarting the builds.

**Comment by no-reply** [comment]
> @jcoyne can you take screenshots of the work and collection show views to confirm the navbars are still present?

@mjgiarlo are you concerned about this? Do you have advice about how to write a spec for this?

**Comment by jcoyne** [comment]
It seems like the specs @mjgiarlo wrote in #1866 should cover this change.

**Comment by no-reply** [comment]
The present failures seem genuine:

https://travis-ci.org/samvera/hyrax/jobs/299891388#L3061-L3064

**Comment by jcoyne** [comment]
@mjgiarlo yes, they are fine.

**Pull request merged**
