### PR TITLE
Update chromedriver helper to the latest minor release

### PR DESCRIPTION
**Pull request by jcoyne**
Remove the temporary pinning that was needed due to upstream bugs.

### CODE REVIEW

**Comment by no-reply** [comment]
@jcoyne what's the status of this work?

**Comment by jcoyne** [comment]
@no-reply abandoned I guess...I didn't have anymore time to work on this.

**Comment by afred** [comment]
@cjcolvar is working on a PR to @jeremyf's  `capybara-maleficient` gem that would allow `capybara` to get bumped to 3.x. Stand by, and look at https://github.com/jeremyf/capybara-maleficent in the meantime.

**Comment by jcoyne** [comment]
I've rebased this to get the changes from #3387

**Pull request closed without merging**
