### PR TITLE
fix circleci config to match masters

### PR DESCRIPTION
**Pull request by orangewolf**
Fixes CircleCI failing on 2.x-stable branch due to chrome driver

Circle CI config continues to evolve and along the way solved the chrome driver issue. This backports that code from master to the 2.x branch.

Changes proposed in this pull request:
* updates .circle/config to match master

Guidance for testing, such as acceptance criteria or new user interface behaviors:
* [best lawyer voice] if the CI don't loose you must approve!

### CODE REVIEW

**Comment by jrgriffiniii** [comment]
I think that `chromedriver` needs to be deprecated in favor of `webdriver`: https://github.com/samvera/hyrax/blob/master/hyrax.gemspec#L108

**Comment by jrgriffiniii** [comment]
Yes, I don't think that https://github.com/samvera/hyrax/pull/3770 was backported.

**Comment by jrgriffiniii** [comment]
Waiting on https://circleci.com/gh/jrgriffiniii/hyrax/699 to pass, then I can issue a PR against this.

**Comment by jrgriffiniii** [comment]
https://github.com/orangewolf/hyrax/compare/v2-circle-update...jrgriffiniii:v2-circle-update-jrgriffiniii?expand=1 should restore the build matrix for Ruby 2.6.2.  I can offer to either merge this or offer a PR against your branch: https://circleci.com/gh/jrgriffiniii/workflows/hyrax/tree/v2-circle-update-jrgriffiniii

**Comment by orangewolf** [comment]
@jrgriffiniii I say merge it, since its a more correct fix

**Comment by orangewolf** [comment]
ok, merged @jrgriffiniii changes in, if this is green we should be gtg.

**Comment by jrgriffiniii** [comment]
The failures look like they might be flapping feature tests: https://circleci.com/gh/samvera/hyrax/4783 so I'm going to keep brute-forcing the build until this is passing

**Pull request merged**
