### PR TITLE
update bullet from PCDM to "fully featured"

### PR DESCRIPTION
**Pull request by vantuyls**
Fixes #issuenumber ; refs #issuenumber

Present tense short summary (50 characters or less)

More detailed description, if necessary. Try to be as descriptive as you can: even if you think that the PR content is obvious, it may not be obvious to others. Include tracebacks if helpful, and be sure to call out any bits of the PR that may be work-in-progress.

Description can have multiple paragraphs and you can use code examples inside:

``` ruby
class PostsController
  def index
    respond_with Post.limit(10)
  end
end
```

Changes proposed in this pull request:
*
*
*

@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by jcoyne** [comment]
https://i.pinimg.com/236x/b6/1f/2b/b61f2baf34e83f92039877aa56e3a98e.jpg

**Comment by jcoyne** [comment]
@vantuyls can you say why this change is being made?

**Comment by mjgiarlo** [comment]
@jcoyne Today's changes to the http://hyr.ax/ manager docs site were driven by a conversation I had with @vantuyls and @julesies about how the frontpage should probably be updated. (Highlighting Fedora 4 and PCDM was a holdover from sufia.io, and was a major selling point from the Sufia 7 push.)

**Comment by vantuyls** [comment]
Making changes to the hyrax homepage to align the site's content with expected users - namely, manager-types who are looking for a relatively high-level overview of what hyrax.

**Comment by jcoyne** [comment]
@mjgiarlo @vantuyls sounds reasonable, I just wanted the reasoning recorded somewhere.

**Pull request merged**
