### PR TITLE
Valkyrie Indexer Setup and Specs

### PR DESCRIPTION
**Pull request by geekscruff**
Note: includes a failing test that need a fix (see below).

Indexer:
* Add :basic_metadata Indexer to `ValkyrieWorkIndexer`
* Add indexing rules to `config/metadata/basic_metadata.yml`
* Add a basic spec for a generated Indexer (`MonographIndexer`)

ActiveFedoraConverter
* Fixes issue with creating a DefaultWork for Valkyrie native resources (ie. those generated via the generator)
* Specs updated for ModelTransformer, ActiveFedoraConverter and Persister
* This persister test now fails and needs fixing: `Wings::Valkyrie::Persister When passing a Valkyrie::Resource that was never an ActiveFedora::Base can save nested resources` with `undefined method `nested_resource_attributes=' for #<Wings::CustomResource::GeneratedResourceSchema:xxxx>`

### CODE REVIEW

**Comment by no-reply** [comment]
this is looking great! thanks for pushing this forward! i'll give a closer review when we get #4219 in and rebase.

**Comment by straleyb** [comment]
Since #4219 is in now, im going to go ahead and publish this PR. Its ready for review.

**Comment by geekscruff** [comment]
I expect one or two tests to fail, so next step is to fix 'em.

**Comment by geekscruff** [comment]
@no-reply I did move the indexer registration to an initializer in the generate indexer PR. I left the statement in the individual indexers for clarity, even though they aren't strictly necessary now. 

So, the failure relating to loading the indexer has been fixed, but the current failure is related to the refactoring of `ActiveFedoraConverter` so I/we do need to have a look at that.

**Comment by no-reply** [comment]
@geekscruff thanks. i'm taking a look

**Comment by no-reply** [comment]
The issue is to do with inheritance of class variables, which impacts `accepts_nested_attributes_for`. i'm working on approaches, but may also just end up writing `DefaultWork` out of existence. it's probably time for that :)

**Comment by no-reply** [comment]
seems connected to https://github.com/samvera/active_fedora/issues/1343

**Comment by straleyb** [comment]
Well, I rebased this onto master and it seems like it picked up on a whole slew of stuff. Not sure why that happened exactly. I can push a new one if needed though since I borked it-ish.

**Pull request closed without merging**
