### PR TITLE
Backport to 3.x - AdminSets need an id to save their associations

### PR DESCRIPTION
**Pull request by orangewolf**
Set up a fallback for the case where NOID is false.

Fixes https://github.com/samvera/hyrax/issues/5788

@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by orangewolf** [comment]
not sure what is making CI mad. This one is the backport, going to try again against main.

**Comment by dlpierce** [comment]
The build is broken because Circle is trying to build the test app with Rails 5.2.8.1 (with the AR store patch) but not blacklight 6.25.1. That's a bit strange since the Circle config implies it is using a specific versions of Rails for the build step.

**Comment by dlpierce** [comment]
Correction, browse-everything 1.2.0 is incompatible with ruby 2.5. The error looked similar to what has been seen in the above case.

**Comment by no-reply** [comment]
should we raise this as an issue with the BE folks? it seems like they should have bumped the major version when dropping ruby 2.5 support?

**Comment by dlpierce** [comment]
Rebased now that 3.x-stable is green again.

**Review by dlpierce — APPROVED** [review]

**Pull request merged**
