### PR TITLE
change default badge color for admin set and user collection

### LINKED ISSUE #2992: Default badge colors for pre-configured collection types should vary
### Descriptive summary

The default colors assigned to User Collection, Admin Set, and default badge color should all be different.

### Rationale

Users should not have to edit pre-configured collection types in order to have different badge colors per type.

### Expected behavior

* Admin Set should have default badge color: '#405060'
* User Collection should have default badge color: '#705070'
* default badge color used when creating a new collection type should be: "#663333"

### Actual behavior

* Admin Set default badge color is: "#663333"
* User Collection default badge color is: "#663333"
* default badge color used when creating a new collection type is: "#663333"  (correct)

### Steps to reproduce the behavior

1. Regenerate the test app
1. Create default admin set
1. Create a user collection
1. Define a new collection type keeping the default badge color
1. Create a collection of the new type
1. Dashboard -> Collections

Verify that the expected colors are used for the badges.

### Related work

Issue #2707, PR #2936 Make badge colors for collection types configurable

### PR DESCRIPTION
**Pull request by blancoj**
Fixes #2992

### CODE REVIEW

**Comment by julesies** [comment]
These all seem the same color on nurax, is that expected? (and assuming I'm looking at the right badge) 
screen shot 2018-05-09 at 12 49 05 pm

**Comment by elrayle** [comment]
@julesies You are seeing the default color.  You can set a per type color by editing each type thru Dashboard -> Settings -> Collection Types -> click each title -> Badge Color

**Comment by elrayle** [comment]
In the future, maybe we should randomly generate a unique color that admins can edit.  (2.1.1)

**Comment by julesies** [comment]
Okay, well i changed a default color and it worked. so it seems good.

**Pull request merged**
