### PR TITLE
Improve the universal viewer deployment

### PR DESCRIPTION
**Pull request by geekscruff**
Based on feedback from @little9 over at [nurax#336](https://github.com/curationexperts/nurax/pull/336)

The uv install can be run with `yarn install` or `rake assets:precompile`.

I'll update the Hyrax Management Guide accordingly.

@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by no-reply** [comment]
This looks great.

@geekscruff is there any action that needs to be taken post-merge for `nurax`?

**Comment by geekscruff** [comment]
@no-reply thanks! nothing for nurax, as I have a PR in to put the new files in place (those come during install which isn't re-run for nurax).

**Comment by no-reply** [comment]
ah, yeah. do we need a rake task to move files around during upgrade?

**Comment by geekscruff** [comment]
@no-reply good idea, I'll get that in early next week

**Pull request merged**
