### PR TITLE
Adds workflow to trigger nurax deploy on push

### PR DESCRIPTION
**Pull request by mlooney**
@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by no-reply** [comment]
note that this adds a new use of GitHub Actions.

is this something we're open to?

**Comment by dlpierce** [comment]
What is the concern? If GH Actions were to become non-free for public repos in the future?

**Comment by no-reply** [comment]
> What is the concern? If GH Actions were to become non-free for public repos in the future?

i think it's mainly just that it's one more pipeline to configure and monitor, and one more configuration format to manage.

i don't have any other github actions projects, so personally i would probably avoid doing maintenance on this.

**Comment by elrayle** [comment]
For context, the purpose of this is to provide an auto-deploy to the DCE supported `nurax-dev` and `nurax-stable` test applications.  It connects into github [actions](https://github.com/curationexperts/nurax/actions) in [curationexperts/nurax](https://github.com/curationexperts/nurax).  Without these, someone would have to manually deploy [nurax-dev](https://nurax-dev.curationexperts.com/) and [nurax-stable](https://nurax-dev.curationexperts.com/). 

I am in favor of merging this PR.

**Comment by elrayle** [comment]
@no-reply Are you open to having this merged?

**Comment by elrayle** [comment]
Discussed today in Tech Call and there are no blockers to this being merged.  There was a question about who would maintain this pipeline.  There are several folks, including DCE staff, that work with Github Actions.  So it seems like there are members of the community that can help maintain this pipeline.  

It is also worth noting that this is not a critical pipeline.  If it fails, it only impacts nurax related deploys.  Additionally there are manual steps to deploy that would address the failure.

**Review by elrayle — APPROVED** [review]
Thanks for adding this.  It will be nice to have the auto-deploys working.

**Pull request merged**
