### PR TITLE
HYRAX-#3293 - Map license to dcterms:license

### PR DESCRIPTION
**Pull request by fritzfreiheit**
Fixes HYRAX-#3293

Change the basic meta data for `license` to the url pointing to the `dcterms:license`

### CODE REVIEW

**Comment by no-reply** [comment]
I think we need to provide a migration script for this, yes? Or else make this configurable, and retain the existing behavior in applications that were generated prior to 3.0.0?

**Comment by no-reply** [comment]
@fritzfreiheit could you provide a commit/PR message for this?

See https://chris.beams.io/posts/git-commit/

**Comment by fritzfreiheit** [comment]
> I think we need to provide a migration script for this, yes? Or else make this configurable, and retain the existing behavior in applications that were generated prior to 3.0.0?

Sorry, but I really don't know the code well enough to do more than nod in agreement. If I had an example of a migration script and configuration to work off of I would be able to answer more intelligently and do the work. Probably someone else should have done the coding for this, as you can see my code was far too simplistic and totally lacks the depth of knowledge to have done it intelligently.

**Comment by fritzfreiheit** [comment]
@no-reply -- You can see the driver for the migration here:
https://github.com/samvera/hyrax/blob/master/app/services/hyrax/works/migration_service.rb

**Pull request merged**
