### PR TITLE
update valkyrie.yml to use fedora adapter for dev/prod

### PR DESCRIPTION
**Pull request by geekscruff**

### CODE REVIEW

**Comment by jcoyne** [comment]
Do we need this?  What if I don't intend to put my resources in Postgresql?  What if I'm using mysql?

**Comment by geekscruff** [comment]
@jcoyne just realised that, was about to post a comment ... currently there's an error if trying to create anything from console or admin_set create task ... I guess we need a way round that?

**Comment by jcoyne** [comment]
@geekscruff but that's only if you have configured it to use the postgresql adapter, right?  I say let's not ship in that configuration.

**Comment by geekscruff** [comment]
@jcoyne I was trying this inside .internal_test_app ... wanted to see how far I could get bringing up rails s, failed at create_admin_set task

**Comment by jcoyne** [comment]
Yes, I'm suggesting that this line is wrong: https://github.com/samvera/hyrax/blob/valkyrie/lib/generators/hyrax/templates/config/valkyrie.yml#L2

**Comment by geekscruff** [comment]
ah, bingo ... is that worth a PR?

**Pull request merged**
