### PR TITLE
Remove unused partial

### PR DESCRIPTION
**Pull request by jcoyne**
The comment in the top said:
> This partial is obsolete and has been renamed for now. Needs cleanup of this and other referenced unneeded items.

### CODE REVIEW

**Comment by jcoyne** [comment]
Worth investigating whether `hyrax/dashboard/collections/_work_action_menu.html.erb` can be removed too.

**Comment by no-reply** [comment]
@elrayle is this blocked pending @adamjarling's review, or is there another way to unblock it?

**Comment by adamjarling** [comment]
@elrayle Regarding the diff between `/hyrax/dashboard/collections/_list_collections.erb.html` and `/hyrax/my/collections/_list_collections.erb.html`, perhaps the`data-source="my"` attribute is/was used for being navigating back to the proper app location once some action occurred?   It doesn't look like the javascript is processing it...

I don't recall adding or working with the attribute `id: "src_copy_link#{id}"`.

As long as everything is working correctly in the UI, this PR seems fine to me.

**Comment by afred** [comment]
@jcoyne looks like someone modified your deleted files, but the consensus among the reviewers here (post tech call review session) is that removing these is ok. Can you re-push and ensure they are deleted?

And @adamjarling if you could submit a review again once that's done, we should be able to merge.

Thanks!

**Comment by adamjarling** [comment]
@afred Sure thing.  I'll keep my eye on it today.

**Comment by elrayle** [comment]
There is an issue to refactor collections to DRY up the code...
https://github.com/samvera/hyrax/issues/1677

**Comment by elrayle** [comment]
Note that you will need to double check that the files being deleted are still showing no diffs from the file with the same name in 

* [app/views/hyrax/my/collections/_list_collections.html.erb](https://github.com/samvera/hyrax/blob/master/app/views/hyrax/my/collections/_list_collections.html.erb)
* [app/views/hyrax/my/works/_list_works.html.erb](https://github.com/samvera/hyrax/blob/master/app/views/hyrax/my/works/_list_works.html.erb)

The other file, app/views/hyrax/dashboard/collections/_form_default_group_delt.html.erb, is clearly obsolete since it is marked so in a comment in the file.

**Comment by afred** [comment]
@elrayle I just confirmed that there were no diffs between the deleted files in the `remove_partials` branch and the most recent versions of those same files in `master`. There were none, so I proceeded with the a rebase (in which I also consolidated the 2 commits into 1), and force pushed the branch.

**Comment by elrayle** [comment]
@afred There are diffs...

Run in the terminal at the root of hyrax on master branch...
```
git diff HEAD:app/views/hyrax/dashboard/collections/_list_collections.html.erb HEAD:app/views/hyrax/my/collections/_list_collections.html.erb
git diff HEAD:app/views/hyrax/dashboard/collections/_list_works.html.erb HEAD:app/views/hyrax/collections/_list_works.html.er
```

NOTE: The lookthru path for dashboard is...
* first look in `app/views/hyrax/dashboard/collections`
* if not found look in `app/views/hyrax/my/collections`
* if not found look in `app/views/hyrax/collections`

**Comment by afred** [comment]
IF this can be changed to only remove `app/views/hyrax/dashboard/collections/_form_default_group_delt.html.erb` then we should be good.

**Comment by randalldfloyd** [comment]
@afred Pushed changes as discussed in yesterday's review: 

Restored 2 of 3 partials that can't be considered obsolete due to conflicts identified by @elrayle 
Rebased and squashed.  

The `travis-ci/push` failed for ` RAILS_VERSION=5.0.6`, but there weren't any actual failing examples and `travis-ci/pr` passed.  Typical Travis annoyance?

**Comment by jcoyne** [comment]
I'm not understanding why a diff is an indicator of the file being used.  Can someone explain it to me?

**Comment by randalldfloyd** [comment]
I was just helping to push along some stale PR's so I'll have to defer to those that had closer eyes on this one.

**Pull request merged**
