### PR TITLE
issue#1552_add_work_btns

### LINKED ISSUE #1552: Collection: Add button to create a work through a collection from the admin show page
### Descriptive summary

Add a button to the collection admin show page that creates a work that when saved is added to the collection.

### Implementation

**Edit File:** 
* [app/views/hyrax/dashboard/collections/show.html.erb](https://github.com/samvera/hyrax/blob/master/app/views/dashboard/hyrax/collections/show.html.erb)

- [x] Modify title of button `Add works`  to be `Add existing works`
- [x] Add a `Add new work` button near the existing renamed `Add existing works` button.  We'll rename and move it to match the mockup in another issue.
- [x] Process the button in a way similar to the following...

* Dashboard -> Repository Content -> Works -> New Work -> fill in requirements and save
* Dashboard -> Repository Content -> Works -> edit the work you just created -> Relationships tab
* click Attach New Work button

This will go through the new work process and when done, the new work will be a member of the first work you created.

We want to do the same thing with the process following...

* Dashboard -> Repository Content -> Collections -> Create a new collection -> fill in requirements and save 
* Dashboard -> Repository Content -> Collections -> click the collection you just created to go to the admin show page
* click `Add new work` button

This will go through the new work process and when done, the new work will be a member of the collection you created.

This means that under the covers, the collection id has to be passed to the new work form and has to be automatically assigned as the parent collection in the relationships tab.

### Mockup

Mockup shown for reference only as to the direction we are moving the admin show page's UI.

admin-collection-show

### Related work

#1427 Collections: Create an admin show view

### PR DESCRIPTION
**Pull request by gordonleacock**
Fixes #1552

Add a button to the collection admin show page that creates a work that when saved is added to the collection.

In _app/views/hyrax/dashboard/collections/show_actions.html.erb:
      <%= link_to t('hyrax.collection.actions.add_existing_works.label'),
                  hyrax.my_works_path(add_files_to_collection: presenter.id),
                  title: t('hyrax.collection.actions.add_existing_works.desc'),
                  class: 'btn btn-default' %>
      <%= link_to( t(:'helpers.action.work.new'),
                  '#',
                  data: { behavior: "select-work", target: "#worktypes-to-create", 'create-type' => 'single' },
                  class: 'btn btn-default'
                  ) %>

In config/locales/hyrax.en.yml:
    collection:
      actions:
        add_existing_works:
          desc: "Add existing works to this Collection"
          label: "Add existing works"
        add_new_works:
          desc: "Add new work to this Collection"
          label: "Add new work"

In spec/views/hyrax/my/collections/_list_collections.html.erb_spec.rb
it 'the line item displays the work and its actions' do
    expect(rendered).to have_selector("tr#document_#{id}")
    expect(rendered).to have_link 'Collection Title', href: hyrax.dashboard_collection_path(id)
    expect(rendered).to have_link 'Edit Collection', href: hyrax.edit_dashboard_collection_path(id)
    expect(rendered).to have_link 'Add existing works', href:
    "/dashboard/my/works?add_files_to_collection=2r36tx526&locale=en"
    expect(rendered).to have_link 'Add new work', 'data-behavior': "select-work", 'data-target':"#worktypes-to-create"
    expect(rendered).to have_link 'Delete Collection', href: hyrax.dashboard_collection_path(id)
    expect(rendered).to have_css 'a.visibility-link', text: 'Private'
    expect(rendered).to have_selector '.expanded-details dd', text: 'Collection Description'
    expect(rendered).not_to include '<span class="fa fa-cubes collection-icon-small pull-left"></span></a>'
  end

@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by gordonleacock** [comment]
Ugh, had some rebasing problems but resolved those with Nabeela.

Not sure if my specs ran properly.

**Comment by elrayle** [comment]
This is great hooking into the new work process.  Can you look into passing through the collection id and auto-selecting it as the parent collection on the new work Relationships tab?

**Comment by elrayle** [comment]
NOTES: 
The tests are failing the rubocop check.  It wasn't clear to me if the failing check is a real error.  We can take a look at it this morning.

@laritakr's modifications to the admin show page in PR #1562 (merged) has some impact on this.  This mostly entails moving your new button to the location just above the work list.  Can you merge your changes into hers?  Also, I think the labels for the buttons have a different translation path.

**Comment by gordonleacock** [comment]
I'm going to rebase and try to finish this off. Unfortunately I won't have time to do anything else this week.

**Pull request closed without merging**
