### PR TITLE
Charts updated

### LINKED ISSUE #2714: Toggle Repository Object Charts
Repository Objects donut chart toggles between Visibility, Work Types, and Resource Types

### Related work

See #2541

### PR DESCRIPTION
**Pull request by lfarrell**
Fixes #2714 ; refs #2541

Adds toggling for admin charts, save the repository objects chart. 

Switches out the un-maintained morris.js lib for chartkick gem with chart.js.
End users get the new charting libraries, but not the toggling ability, even without the analytics flipper, as the new library needs data in a different format. Charts, should basically look the same

screen shot 2018-03-06 at 10 39 12 am

@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by mcritchlow** [comment]
Overall this LGTM :+1: 

Related to my current PR in #2771 , I'd be interested to see whether the finders added will do the trick for what you need in https://github.com/samvera/hyrax/blob/827abed05ebaa86ea60d37d912f3e6403e685fb2/app/presenters/hyrax/admin/user_activity_presenter.rb#L36 or if we need to customize things a bit more.

**Comment by mcritchlow** [comment]
@vantuyls - I'm curious about the graph reference above for the user graph. There's a method in there (see above) that references `returning_users` which @lfarrell has included in the graph.

That reference appears to have been put in when the class was created for https://github.com/samvera/hyrax/issues/430

but i'm curious if we're conflating stats here. The notion of new registered users and "returning users" from a remote service like Google or Matomo is a pretty different concept.. I guess what I'm wondering is what story we want that graph to tell.

**Comment by vantuyls** [comment]
so, the graph in question is trying to capture total users (though we probably mean sessions) and returning users (sessions) for the time period. maybe i'm not understanding the question?

**Comment by mcritchlow** [comment]
@vantuyls - my concern is that the currently implemented ["New Users" query](https://github.com/samvera/hyrax/blob/827abed05ebaa86ea60d37d912f3e6403e685fb2/app/presenters/hyrax/admin/user_activity_presenter.rb#L30-L33) that is already in use has nothing to do with the analytics concept of users/sessions, but is actually executing a query for the number of [registered users](https://github.com/samvera/hyrax/blob/827abed05ebaa86ea60d37d912f3e6403e685fb2/app/services/hyrax/statistics/users/over_time.rb#L20), with the site for the given date range.  

So perhaps the current query needs to be changed so both queries come from the new (remote) analytics?

**Comment by vantuyls** [comment]
ah, i see what you mean. Yeah, it make sense to me to pull those two datasets from the same data stream (GA or MATOMO). So that would be "Total Users" and "Total New Users" for whatever the time period is?

**Comment by mcritchlow** [comment]
@vantuyls I think so yes, though we might need to use Analytics language like "Unique Visitors" (or "New Visitors" and "Returning Visitors" or something like that. My concern with using the work User it might make people think of registered users (the current behavior). That said, I think this issue isn't directly related to @lfarrell's PR, so I've created a separate ticket https://github.com/samvera/hyrax/issues/2776 that I'm happy to work on if we're on the same page for desired behavior.

**Pull request merged**
