### PR TITLE
Updates the chromedriver-helper dependency to 2.1 releases and removes the CircleCI step for running headless Chrome manually

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Refs #3373

### CODE REVIEW

**Comment by jrgriffiniii** [comment]
The build for my fork on this branch passed: https://circleci.com/gh/jrgriffiniii/hyrax/5

**Comment by no-reply** [comment]
@jrgriffiniii any idea why this PR didn't get a circle build?

**Comment by jrgriffiniii** [comment]
"Build forked pull requests" was disabled on https://circleci.com/gh/samvera/hyrax/edit#advanced-settings

**Comment by jrgriffiniii** [comment]
I rebased for some whitespace commits and force-pushed after adjusting the settings, it's running now on CircleCI.

**Comment by no-reply** [comment]
ty!

**Comment by jrgriffiniii** [comment]
CircleCI finally passed for this: https://circleci.com/gh/jrgriffiniii/hyrax/16?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Pull request merged**
