### PR TITLE
breaks very long metadata field values on show page

### LINKED ISSUE #2976: metadata description fields don't break words properly
### Descriptive summary

Metadata description fields with values that are very long strings of text, don't break the words properly which causes the page rendered to look bad. See attached screenshot.

### Rationale

Enforce CSS rules to keep the layout of the page looking as it is intended.

### Steps to reproduce the behavior

1. Create a new work
1. Type in a very long string of unbroken text. Here, let me provide one:
```
This..is..a..long..bit..of..unbroken..text!This..is..a..long..bit..of..unbroken..text!This..is..a..long..bit..of..unbroken..text!This..is..a..long..bit..of..unbroken..text!This..is..a..long..bit..of..unbroken..text!This..is..a..long..bit..of..unbroken..text!This..is..a..long..bit..of..unbroken..text!This..is..a..long..bit..of..unbroken..text!This..is..a..long..bit..of..unbroken..text!This..is..a..long..bit..of..unbroken..text!This..is..a..long..bit..of..unbroken..text!This..is..a..long..bit..of..unbroken..text!This..is..a..long..bit..of..unbroken..text!This..is..a..long..bit..of..unbroken..text!This..is..a..long..bit..of..unbroken..text!This..is..a..long..bit..of..unbroken..text!This..is..a..long..bit..of..unbroken..text!This..is..a..long..bit..of..unbroken..text!This..is..a..long..bit..of..unbroken..text!This..is..a..long..bit..of..unbroken..text!This..is..a..long..bit..of..unbroken..text!This..is..a..long..bit..of..unbroken..text!This..is..a..long..bit..of..unbroken..text!This..is..a..long..bit..of..unbroken..text!This..is..a..long..bit..of..unbroken..text!This..is..a..long..bit..of..unbroken..text!
```
1. View the work

screen shot 2018-04-27 at 1 14 33 pm

### PR DESCRIPTION
**Pull request by revgum**
Fixes #2976 

A few basic rules to break words and maintain the layout of the page. See example screenshot:

screen shot 2018-04-27 at 1 29 29 pm

@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by no-reply** [comment]
Thanks @revgum. Do you mind making changes to satisfy Hound?

Can someone from @samvera/hyrax-ui-ux-advisors review?

**Comment by chrisdaaz** [comment]
looks good to me, thanks!

**Comment by elrayle** [comment]
@revgum I tried out this branch and the text still runs off the edge of the screen.  From the screen shot, it looks like there are no spaces between words, but you are using `..` as a word separator instead.  Did I interpreted your test data correctly?

**Comment by cjcolvar** [comment]
@elrayle I tested locally and it works for me.

**Comment by revgum** [comment]
the last hound violation seems like one we should ignore, it's related to the naming convention of work type properties rendered on the page. Can @samvera/hyrax-code-reviewers verify?

**Comment by cjcolvar** [comment]
@revgum I'd ignore that hound issue since that seems like a refactor change which would need to be done delicately or wait for a major release to break compatibility.

**Pull request merged**
