### PR TITLE
Backport e45b885 citation period fix

### LINKED ISSUE #1333: Citation formatting punctuation
### Descriptive summary

APA and MLA formats include extra trailing period for citations lacking publication information.

### Rationale

`As a` user
`I want` correctly formatted citations
`So that I can` copy and paste into other documents

### Expected behavior

There shouldn't be extraneous punctuation marks.

### Actual behavior

screen shot 2017-07-11 at 3 36 17 pm

[Relevant code snippet](https://github.com/samvera/hyrax/blob/master/app/helpers/hyrax/citations_behaviors/formatters/apa_formatter.rb#L14).

### Steps to reproduce the behavior

1. Create new work, omit publisher and date created attributes
1. On work show page, click `citations`

### Related work

https://github.com/uclibs/scholar_uc/issues/1411

### PR DESCRIPTION
**Pull request by crowesn**
Fixes #1333 
RelatedPR: #1372 

This is a hyrax 1.0 backport of changes made to master in https://github.com/samvera/hyrax/pull/1372

Changes proposed in this pull request:
* Tweak citation formatters to stop adding periods to ends of citations/ group periods with pub data
* Add spec

@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@crowesn If you want to create a new PR that backports the relevant commits from `master` using `git cherry-pick`, you can use this link: https://github.com/samvera/hyrax/compare/1-0-stable...backport_1372?expand=1

**Comment by crowesn** [comment]
Oh that's cool - did you cherry-pick from multiple commits? Shall I close this PR?

**Comment by mjgiarlo** [comment]
@crowesn Hi! Yes, I did. I looked at the diff between the APA formatter in `master` vs `1-0-stable` and pulled in the three commits (only bits and pieces of the middle one, though). Yeah, feel free to close this PR and open a new one. Thanks for taking this on! (The cherry-pick will make it easier in the future to reconcile diffs between the two branches.)

**Comment by crowesn** [comment]
@mjgiarlo 
There's one small problem with the cherry pick - it includes a breaking conflict in the spec that I think would require a new commit. The solr field name on this [line](https://github.com/samvera/hyrax/blob/1-0-stable/spec/views/hyrax/citations/work.html.erb_spec.rb#L16)  changes between master and 1-0-stable and I don't think I can change it as part of a clean cherry pick.

(The solr field label changes from based_near_tesim to based_near_label_tesim in spec/views/hyrax/citations/work.html.erb_spec.rb apa_formatter.rb)

I don't think I can get at this without a commit? 

thanks for wading into git foo with me.

**Comment by dsa-cincy-github** [comment]
@mjgiarlo I could do the cherry pick and then a commit on top with the change to the solr field name?

**Comment by crowesn** [comment]
@mjgiarlo I could do the cherry pick and a commit on top of that with the change to the solr field name?

**Comment by mjgiarlo** [comment]
@crowesn I think it's OK to toss a commit on top, since cherry-picking all the `based_near` changes seems out of scope for this change.

**Comment by crowesn** [comment]
Sweet, thanks.


On Jul 27, 2017, at 1:41 PM, Michael J. Giarlo <notifications@github.com<mailto:notifications@github.com>> wrote:


@crowesn<https://github.com/crowesn> I think it's OK to toss a commit on top, since cherry-picking all the based_near changes seems out of scope for this change.

**Comment by crowesn** [comment]
Closed in favor of #1397

**Pull request closed without merging**
