### PR TITLE
Remove update profile

### LINKED ISSUE #1096: User profile: ‘refresh directory info’
### Descriptive summary

In the User Profile  ‘refresh directory info’ isn’t very intuitive - could it be renamed?

Also it should be hidden when not relevant, eg. when local user accounts are being used.

### PR DESCRIPTION
**Pull request by jcoyne**
This didn't actually have a working implementation in Hyrax.

Fixes #1096

@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by mjgiarlo** [comment]
The effect of this PR is to remove a checkbox in Hyrax that does nothing and probably confuses users. It also removes some functionality that ScholarSphere may be using.

@awead @cam156 @mtribone How much will this impact the ability in ScholarSphere to update attributes from LDAP? I'm not sure how much of this code ever belonged in Sufia, or was used -- I suspect most of the working code here is in ScholarSphere. If we remove this, can you still satisfy the "update attrs from LDAP" use case via e.g., overriding `ProfilesController#update`? I want to gauge the amount of work this is going to cause you folks to do before approving this PR.

**Comment by awead** [comment]
@mjgiarlo @cam156 is out until next week, but I don't see a reason to keep this in. Directory information is going to be different per implementor and seems more locally-oriented. That said, it's still a feature we use and would need to re-implement if we were to move to Hyrax.

**Comment by mjgiarlo** [comment]
@awead No rush. Happy to wait on @cam156's review!

**Comment by mjgiarlo** [comment]
@cam156 Thoughts?

**Comment by jcoyne** [comment]
@cam156 there is no hook. You'd have to prepend a module to the `ProfilesController` that overrode some methods.  I don't think this is a common enough use case (anyone besides PSU?) to justify writing in some sort of configuration for this.

**Comment by mjgiarlo** [comment]
@jcoyne The pre-pended module would likely only have to override `#update`, right?

**Comment by jcoyne** [comment]
@mjgiarlo Yes, just that method.

**Comment by mjgiarlo** [comment]
@cam156 Hi! Do you care to follow up given the method of extension has now been described?

**Comment by cam156** [comment]
@mjgiarlo We are using prepend to override other things in hyrax, so if that is the new described approach for making updates go for it.  I must say I am not entirely in love with the PFM of prepends, but they do work in a pinch and are better than copying over the entire class.

**Comment by mjgiarlo** [comment]
@cam156 OK. Can you say what you don't like about the prepend method of extension? (I'm not sure what "PFM" is, sorry!)

**Comment by jcoyne** [comment]
Well, surely PFM = pure fantastic magic, right? 😉

**Comment by mjgiarlo** [comment]
Hmmm, how is `Module#prepend` more :sparkles: than `Module#include`?

**Comment by cam156** [comment]
@mjgiarlo becuase it is configured away from the code.  It is monkey patching with rails support.

**Comment by mjgiarlo** [comment]
@cam156 OK.

**Pull request merged**
