### PR TITLE
Improved docs for Sipity::Entity

### PR DESCRIPTION
**Pull request by bess**
Add an example of how to find the `Sipity::Entity` for a work

@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by mjgiarlo** [comment]
:policeman: failed the build.

**Comment by mjgiarlo** [comment]
@bess Is this a good candidate for backporting to `1-0-stable`? I see you've backported other Sipity stuff to 1.x, which is great. Also cc: @dheles who has already begun the process to release 1.0.3. Maybe this could be backported to 1.0.4?

**Comment by bess** [comment]
@mjgiarlo I think we did that already: https://github.com/samvera/hyrax/pull/1361

**Comment by dheles** [comment]
yep. it's in the mix for tomorrow's release

**Comment by mjgiarlo** [comment]
Ah. Excellent!

**Pull request merged**
