### PR TITLE
Use collection title in delete confirmation

### PR DESCRIPTION
**Pull request by laritakr**
Replace collection id with collection title in confirmation and error flash notices after collection deletion.

Completes https://github.com/samvera/hyrax/issues/2997

@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by elrayle** [comment]
@vantuyls @samvera/hyrax-repo-managers  Can I get confirmation that it is desired to show title instead of id?  The other option is to show both title and id.  The review group was leaning toward going with title for 2.1.0.

**Comment by no-reply** [comment]
This PR changes the method signature on the callbacks. These were introduced in 18557e5ee4, so I think we are at liberty to change them prior to release.

However, it seems pretty late in the release process for method signature changes and I'd like to make sure we discuss this as @samvera/hyrax-code-reviewers.

Apart from the late change, is `#after_destroy(title:)` the interface we want to move toward? Do we envision use cases for `#after_destroy` that use data other than the title?

**Comment by vantuyls** [comment]
im in favor of seeing title. collection IDs are, i think for most use cases, opaque enough to be useless in an alert message.

**Comment by mjgiarlo** [comment]
If collection title is a multi-valued field, would the first title suffice here?

**Comment by vantuyls** [comment]
ugh. with ordering not enforced, this can create confusion. I'd rather show all values of title to help with clarity.

**Comment by laritakr** [comment]
You DO realize how long titles can be, and how large this flash message could become, right?

**Comment by julesies** [comment]
@laritakr can we truncate the title? I think that would be more meaningful to a deleter than the id.

**Comment by vantuyls** [comment]
100 characters?

**Comment by laritakr** [comment]
screen shot 2018-05-02 at 2 51 44 pm

**Comment by julesies** [comment]
i was testing this earlier, and have a few more thoughts. I think it already warns you before deleting like this which is very helpful. I think the flash message is also helpful because it lets the user know the operation was successfully completed. Even if you can't do anything about it, it's nice to know if it succeeds or fails. The collection ID is sort of confusing to the user, if title is problematic wouldn't it be ok to just say "the collection was successfully deleted"?

**Comment by laritakr** [comment]
Removing the title is definitely the easiest thing if you're ok with that.  

Yes it does warn you before, and I could add the title there instead. But I don't know if there is a size limit, and it's obviously easier not to add variables into that message.

So the decision is just to remove the id AND title info and use a simple confirmation message that the collection was deleted?

**Pull request merged**
