### PR TITLE
add checked option to radio button

### PR DESCRIPTION
**Pull request by kirkkwang**
## Summary
Through radio buttons, give indicator what visibility the collection is currently set to. Tested change on Hyku.

Changes proposed in this pull request:
* add checked option to radio button

### Screenshot
hyrax-radio-button

### CODE REVIEW

**Review by cjcolvar — DISMISSED** [review]
Looks good!

**Comment by no-reply** [comment]
looks like the specs need updating to match the change?

**Comment by cjcolvar** [comment]
FWIW I tried this out locally and I'm not able to reproduce the original issue with hyrax's main branch, but I am able to reproduce it with nurax-dev.

**Comment by no-reply** [comment]
@cjcolvar looking closer, it seems like the form should prepopulate this data?

**Comment by cjcolvar** [comment]
@no-reply Do you think the form is already prepopulating in some cases but not for others?  Could this be a valkyrie/activefedora form difference?

**Comment by dlpierce** [comment]
Thanks Kirk! I ended up solving this in #5812 before I saw this PR. It was also solved by hyrax-head 12 which is why it wasn't showing up on main after the big hyrax 4 merge.

**Comment by kirkkwang** [comment]
Great thank you, @dlpierce !

**Pull request closed without merging**
