### PR TITLE
Remove data.user when instantiating a "Work" object

### LINKED ISSUE #1429: Search for "Child Works" fails in Hyrax 1.0.3
### Descriptive summary

In Hyrax (1.0.3) when searching for works in the Relationships tab of a work edit page using the AJAX widget https://github.com/samvera/hyrax/blob/1-0-stable/app/views/hyrax/base/_find_work_widget.html.erb
the search fails and the application throws the 500 Internal Server Error linked here:
https://gist.github.com/whunter/52358910ac2547d87797fcd5ec287dbb

### Expected behavior

App should return results of search query

### Actual behavior

Search fails because of server error in AJAX request

### Steps to reproduce the behavior

1. Navigate to the edit page of a work
2. Click on "Relationships" tab
3. Enter at least two characters in the "Child Work" text box.

### PR DESCRIPTION
**Pull request by whunter**
Fixes #1429 

Present tense short summary (50 characters or less)

Removes data.user param from Work instantiation in AutoComplete class.
https://github.com/samvera/hyrax/blob/1-0-stable/app/assets/javascripts/hyrax/autocomplete.es6 

The Work constructor is only expecting 3 params, not 4.
https://github.com/samvera/hyrax/blob/1-0-stable/app/assets/javascripts/hyrax/autocomplete/work.es6

@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by jcoyne** [comment]
Has this work already been done in the master branch?  Is there a commit there that could be backported instead?  We don't want the branches to diverge on fixes if at all possible.

**Comment by whunter** [comment]
Hi @jcoyne. I have to confess, I'm not familiar with backporting fixes. Not really sure how that is accomplished. I can definitely see the logic in not wanting your branches to diverge though. 

As far as I can tell this fix has been done in master. It looks like it happens over two commits.

The first removes the data.user param
https://github.com/samvera/hyrax/commit/ef42a417d126d21f657aba4d1cdbc574fd1c6e55

The second changes the third param to reference the correct data attribute.
https://github.com/samvera/hyrax/commit/8a0a956d09b81b1ad47f1a44399133cd422a91cd
Note that this commit also makes changes to several ruby files. I haven't had a chance to test if those changes are compatible with 1-0-stable.

If you could let me know how you'd like me to proceed on this I'd be happy to make some further changes.

As always, thank you for your attention to this!

**Comment by mjgiarlo** [comment]
@whunter I'd be happy to help w/ this. Have time this afternoon?

**Comment by whunter** [comment]
@mjgiarlo I might be able to find some time around 3 (east coast) This week is crazy though. Early next week might be more realistic. Does this just involve cherry-picking those two commits into a branch that's based on 1-0-stable and testing it out?

**Comment by jcoyne** [comment]
@whunter that's exactly right.

**Comment by mjgiarlo** [comment]
@whunter Yeah, what @jcoyne said. Want to give it a shot and ping me if you have questions or run into troubles?

**Comment by whunter** [comment]
@jcoyne @mjgiarlo I've cherry-picked those two commits into my branch and tried it out. Works correctly for me. Please let me know if there is anything else that I should do on this. Thanks!

**Comment by atz** [comment]
@mjgiarlo look ok?

**Comment by mjgiarlo** [comment]
Thanks, @whunter!

**Pull request merged**
