### PR TITLE
Fix flappy feature specs

### LINKED ISSUE #1226: Intermittent test failure
I suspect we need to change `empty?` to `blank?`
```
  1) leases managing leases shows lists of objects under lease

     Failure/Error: <td class="title"><%= link_to curation_concern, edit_lease_path(curation_concern) %></td>

     

     ActionView::Template::Error:

       undefined method `empty?' for nil:NilClass

     # ./app/views/hyrax/leases/_list_active_leases.html.erb:9:in `block in __home_travis_build_samvera_hyrax_app_views_hyrax_leases__list_active_leases_html_erb__1918967764296208783_226972580'

     # ./app/views/hyrax/leases/_list_active_leases.html.erb:6:in `each'

     # ./app/views/hyrax/leases/_list_active_leases.html.erb:6:in `__home_travis_build_samvera_hyrax_app_views_hyrax_leases__list_active_leases_html_erb__1918967764296208783_226972580'

     # ./app/views/hyrax/leases/index.html.erb:14:in `__home_travis_build_samvera_hyrax_app_views_hyrax_leases_index_html_erb__2642505232786911392_227003440'

     # ./spec/features/lease_spec.rb:39:in `block (3 levels) in <top (required)>'

     # ------------------

     # --- Caused by: ---

     # NoMethodError:

     #   undefined method `empty?' for nil:NilClass

     #   ./app/views/hyrax/leases/_list_active_leases.html.erb:9:in `block in __home_travis_build_samvera_hyrax_app_views_hyrax_leases__list_active_leases_html_erb__1918967764296208783_226972580'

Finished in 16 minutes 13 seconds (files took 13.29 seconds to load)

2314 examples, 1 failure, 11 pending

Failed examples:

rspec ./spec/features/lease_spec.rb:38 # leases managing leases shows lists of objects under lease

Randomized with seed 15788
```

### PR DESCRIPTION
**Pull request by mjgiarlo**
Fixes #1226

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@jcoyne I *assume* this is the right `empty?` to replace with `blank?`

**Comment by mjgiarlo** [comment]
I'll re-run the build a few times to see what happens.

**Comment by jcoyne** [comment]
@mjgiarlo this is one of them. I think we also need to get `app/views/hyrax/embargoes/_list_expired_active_embargoes.html.erb` too.

**Comment by mjgiarlo** [comment]
@jcoyne done.

**Pull request merged**
