### PR TITLE
Pass resource to the after_save persister hook

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by cjcolvar** [comment]
Should it get passed to all hooks for consistency?

**Comment by jcoyne** [comment]
It's only necessary in the after_save hook, because the save gives it the ID.  The change_set.resource does not have the ID.

**Comment by cjcolvar** [comment]
Would an alternative be to reload the resource in the change set?  Or would that confuse the change set?
A small comment like what you just said might be useful if passing the resource.

**Comment by carrickr** [comment]
Resource could be changed with `change_set.model[:resource] = `.  I suppose the question is are the use cases focused on having the change_set, previous resource, and the new resource for a hook or do they focus on just the new resource and changes?

**Comment by jcoyne** [comment]
@cjcolvar A change set should not be mutable.  It represents the prior state.  The updated resource is the subsequent state.

**Comment by cjcolvar** [comment]
:+1: that clears things up.

**Pull request merged**
