### PR TITLE
Use Queries#find_members instead of old FileSet#files

### PR DESCRIPTION
**Pull request by cjcolvar**

### CODE REVIEW

**Comment by jcoyne** [comment]
@cjcolvar looks like there's a conflict to be resolved.

**Comment by cjcolvar** [comment]
@jcoyne I think I resolved it.

**Comment by jcoyne** [comment]
I'm still seeing `This branch cannot be rebased due to conflicts` 😿

**Comment by cjcolvar** [comment]
Huh, it looks good to me.

**Comment by jcoyne** [comment]
Ah, it's only when the merge type selector has been changed to "Rebase and merge"

**Pull request merged**
