### PR TITLE
[WIP] begin adding catalan translations (for @vantuyls)

### PR DESCRIPTION
**Pull request by mjgiarlo**
This is the beginning of Catalan translations. Steve Van Tuyl has a colleague who has offered to make Catalan translations, and will start by reviewing the machine translations.

### CODE REVIEW

**Comment by vantuyls** [comment]
@clarallebot see up there...

**Comment by jcoyne** [comment]
This seems stale. Are we going to pick this back up?

**Comment by vantuyls** [comment]
just contacted @clarallebot about this. will get back on the response.

**Comment by mjgiarlo** [comment]
@vantuyls assuming this goes well, we may also want to encourage follow-on work to add Catalan to some of our dependencies (Blacklight comes to mind).

**Comment by mjgiarlo** [comment]
@clarallebot Certainly, yes! Thank you.

**Comment by jenlindner** [comment]
Hi @clarallebot, it would be great to get this into Hyrax :-) Are you still working on it? If not, do you think it could go in as is?

**Comment by vantuyls** [comment]
i just pinged @clarallebot on this. if we can't get this unstuck in the next few weeks, maybe we ought to close this and open a new pr later when she has more time?

**Comment by mjgiarlo** [comment]
@vantuyls Makes sense to me. It may make sense to do the work in Blacklight first, since Hyrax uses its translations: https://github.com/projectblacklight/blacklight/tree/master/config/locales

**Comment by vantuyls** [comment]
closing until we can get @clarallebot or another Catalan speaker to review.

**Pull request closed without merging**
