### PR TITLE
Fix translations in german locale file

### PR DESCRIPTION
**Pull request by jzimpel**
As a native german speaker I found some literal translations in the german locale file that do not fit the context.

It' s not a complete review of the locale, just a few that caught my attention when updating hyrax to v3.4.1

@samvera/hyrax-code-reviewers

### CODE REVIEW

**Review by cjcolvar — APPROVED** [review]
Thanks for fixing these!

**Review by cjcolvar — CHANGES_REQUESTED** [review]
Thanks for your contribution!  I need to check on CLAs before I'm able to merge this.

**Comment by cjcolvar** [comment]
@jzimpel I don't see CLAs on file for you.  Unfortunately I believe the current Samvera policy requires CLAs even for this kind of contribution.  Fortunately though, the Samvera board is considering removing this requirement at its meeting later this month.  If you don't want to wait until then to get this PR merged then you'll have to submit a [cCLA and iCLA](https://samvera.atlassian.net/wiki/x/AwonG).  Sorry!

**Comment by jzimpel** [comment]
Ok, I'll have a look at it. Thanks so far!

**Review by cjcolvar — APPROVED** [review]

**Comment by cjcolvar** [comment]
The CLA requirement has been dropped so nothing is blocking this now.  Thanks for the contribution!

**Pull request merged**
