### PR TITLE
Exploration: Deno in Hyrax?!?

### LINKED ISSUE #5313: Use Webpacker for JavaScript assets
### Descriptive summary

Webpacker is the contemporary solution for processing and bundling JavaScript files in Rails. Hyrax should switch to using it.

### Rationale

I don’t *love* having to file this issue (or use Webpack), but on investigation it turns out that the [`babel-source` gem](https://rubygems.org/gems/babel-source) used to support Ecmascript 6+ in Sprockets only supports Babel version 5 (last updated in January 2016). This means that the past six years of JavaScript developments are unavailable to us. (Babel is currently on version 7.16.)

Anybody who comes to Hyrax development having learned Javascript in the past few years will be surprised and confused why [certain expected features](https://babeljs.io/docs/en/plugins-list#es2022) fail to work.

### Expected behavior

Modern JavaScript code can be compiled and used by Hyrax.

### Actual behavior

A `SyntaxError` if you try to use any syntax which was not available for the final release of Babel 5.

### Related work

See #3920.

### PR DESCRIPTION
**Pull request by marrus-sh**
This is an exploratory PR for using Deno as a JavaScript bundler with Hyrax.

**Update:** I’ve written a more accessible introduction to this PR here: https://ucsb-library.gitlab.io/notes/~kibigo/2022-01-10/deno-rails/

### Background

The recommended way of including “contemporary” (post‐ES2016) JavaScripts in a Rails Engine is to [publish the JavaScripts as an NPM package](https://guides.rubyonrails.org/webpacker.html#webpacker-in-rails-engines) and tell applications to require that package on their end. This approach is unsatisfactory to me for the following reasons :—

01. Even in the simplest case where we are just using GitHub as our publishing location, it requires creating and maintaining a `package.json` file, which adds complexity to our release process.

02. Hyrax JavaScripts aren’t intended to be used independently from the Hyrax application, so publishing them separately seems strange.

03. Using NPM as part of our JavaScript build process encourages participation in the NPM ecosystem, which is a hellish landscape of dependencies and a maintenance nightmare over the very long term.

04. Hyrax applications will *also* be required to participate in the NPM ecosystem and use supporting JavaScript bundling mechanisms, which could potentially create difficult work for existing applications. Ideally we have a solution which “just works” with minimal configuration by end‐users.

Instead of using NPM, I wondered if it might be possible to follow the same approach we used for Universal Viewer (see #3696) and simply bundle our JavaScripts to a well‐known location in `public/`, which Hyrax applications can then include as necessary. This could work in concert with our existing Sprockets‐based approach, easing the transition between the two methods. JavaScripts using the new method are placed in `app/scripts` (and/or `lib/scripts`); old ones are still available in `app/assets/javascripts`.

Because it is the absolute simplest solution from a maintenance perspective, the mechanism I chose for this exploration was [Deno](https://deno.land). This is *not* to say that Deno is the only option—the Universal Viewer approach linked above was implemented using Yarn, and a Yarn‐based approach has smaller installation costs (but larger maintenance ones). My hope is that the techniques in this PR can be adapted as necessary to fit whichever solution is deemed best.

This is simply an architectural change which *should not* have any immediate impact on codebase operation. Fixes #5313 and paves the way for work on #5298 and other issues with Hyrax’s Javascripts.

#### The good

+ Single binary dependency.

+ Import files using ordinary Javascript `import` statements.

+ Will make JavaScript developers happy.

+ No `package.json` to maintain or publishing source to configure.

+ Builtin formatting (`deno fmt`), linting (`deno lint`), and testing (`deno test`).

+ Support for typechecking and type annotations.

+ Can (and should) be used side‐by‐side with the existing Sprockets asset pipeline.

+ Callable via Rake tasks; can be trivially made a dependency of `assets:precompile`.

#### The bad

+ Doesn’t ship with Rails, so this is one more thing for users to install.

    + The installation is fairly trivial on most platforms. It is *not* trivial on Alpine Linux (see below), so it may introduce problems for Alpine users who are *not* using our Dockerfile.

+ Because this solution doesn’t use the Rails asset pipeline… it can’t use the asset pipeline. This means no automatic reloading, integration with Sprockets, et cetera. *Not all scripting will be able to be converted over to this new method.*

    + The hope is that the scripts in `app/assets/javascripts` are kept minimal and exist only for integration with other gems (e.g. Blacklight) while the scripts in `scripts/` contain the bulk of necessary Hyrax code.

+ `deno bundle` is very basic, with no transpilation and only simple minification. However…

    + Transpilation shouldn’t be necessary, as we only officially target the latest versions of Chrome, Firefox, Edge, and Safari, and it is easy to write code which works in all of those browsers.

    + This can always be changed later by inserting an additional step after `deno bundle`.

+ No support for CoffeeScript. (We don’t use CoffeeScript right now anyway.)

#### The ugly

+ Deno requires glibc, which isn’t provided in Alpine Linux. See denoland/deno#3711.

    + There is a workaround for this (obviously; see the `Dockerfile`), but it isn’t pretty.

+ At present, all the Deno‐related scripts (including testing) are run with `rake` from the application directory. This contrasts with our Rails specs, which are run from the engine directory.

    + This is probably fixable in one direction or the other.

### List of Changes

+ Update the `Dockerfile` to install `deno` alongside everything else. This requires some shenanigans for Alpine Linux.

+ Add `deno.json` and create a new `Hyrax` class to replace the old `Hyrax` object, with one test to ensure that everything works.

+ Provide Rake tasks for interacting with Deno and update the install generator.

+ Install necessary components into `.dassie`.

+ Add a CI task for running Deno tests.

+ Remove the existing eslint stuff, since `deno lint` now handles that during CI.

+ Loads the bundled javascripts as `type="module"`, and adds a `defer` attribute to the application javascripts to ensure they run after ours.

### Manual Upgrade for Existing Applications

01. Install Deno (1.17.1 or later).

    + If you are on Alpine Linux, you will need to install [alpine-pkg-glibc](https://github.com/sgerrand/alpine-pkg-glibc) in order for Deno to run.

02. Run `bundle exec rake hyrax:deno:install` from the application directory to make Deno available to Rails.

    + This only needs to be run *once* and simply generates the `bin/deno` script.

03. Run `bundle exec rake hyrax:deno:bundle` (or `bundle exec rake assets:precompile`) from the application directory to bundle assets.

    + This needs to be run *every* time JavaScript assets change (it’s fast).

    + Bundled scripts are placed in `public/scripts/hyrax.js`.

### Considerations for Testing

+ Ensure that newly‐generated apps function correctly.

+ Ensure that the manual upgrade steps listed above work for existing Hyrax users.

+ Ensure that this didn’t break the existing Javascripts somehow!

### Currently Broken

+ Some feature tests, presumably because CI hasn’t yet been updated to generate the Deno bundle for Ruby testing. (A `deno-build` job using the `denoland/deno` docker image is probably the easiest way of making this happen.)

+ Jasmine tests, probably, for the same reason.

### CODE REVIEW

**Comment by marrus-sh** [comment]
houndci please don’t 😩

**Comment by no-reply** [comment]
this all looks pretty good on its face. i added it to the Samvera Tech agenda for this 2022-01-05 for discussion. 

https://samvera.atlassian.net/wiki/spaces/samvera/pages/1888682027/Samvera+Tech+Call+2022-01-05

i'll try building a new app with this shortly and see where that takes me.

**Comment by orangewolf** [comment]
@marrus-sh I wonder if you have opinions about this when it comes to viewing things through the lens of Rails 7? I'm a little concerned we might be skating to where the puck was instead of where it is going here.

**Comment by jrochkind** [comment]
Note that I think it’s not entirely true anymore that “the recommended way to includeJavaScripts in a Rails Engine is to publish the JavaScripts as an NPM package.”

I think with the new Rails 7 jsbundler stuff (which can be used in some pre-Rails 7), dhh wants you to use import-maps eg https://github.com/rails/importmap-rails#composing-import-maps

(Yes, lots of Rails docs are not synchronized and are at various different points on Rails, um, JS journey).

Whether this makes sense or will work better/worse for hyrax I don’t know. The Rails JS story has gotten very confusing.

**Comment by jrochkind** [comment]
With Rails moving to “do JS bundling however the heck you want”, I’m not sure how much of a problem it is if an engine (whether an “in control” one like hyrax or otherwise) ends up being compatible with the various choices. 

Rails is now saying the recommended way is importmaps, but you can also use webpacker, esbuild, or others via jsbundling-rails.  For Rails 7... but all these options are available in Rails 6 too, just by adding the importmaps-rails and/or jsbundling-rails dependencies. I think. It's a bit confusing.  even finding docs that _explain_ it is hard... here's one that might still be accurate? https://noelrappin.com/blog/2021/09/rails-7-and-javascript/

How does an engine provide JS that can work regardless of what method the app wants to use for JS bundling? Or is it not necessary to do that, especially for an engine like hyrax that's kind of "all encompassing", you can just say "the app has to do it our way"?  I'm not sure. 

I'm still confused about how Rails own engines that have JS, like ActionCable or ActiveStorage, will be providing JS -- I guess importmaps since that's dhh's favorite?  But then what if an app wants to use Webpacker or esbuild and ActionCable/ActiveStorage... ?  I'm still very confused about Rails vision.

**Comment by marrus-sh** [comment]
@orangewolf I started by looking into how Rails 7 does things, and this is what i found :—

- Tools like `webpacker`, `jsbundler-rails`, et cetera do not play well with Rails engines. There used to be documentation for using Webpacker with engines, but it was removed from the latest version. jsbundler seems to view it as infeasible. The recommendation is to use Sprockets (or NPM…).

- Sprockets itself does not appear to support any JavaScript features not supported by Babel 5 (which is to say, introduced in the last 7 years), and it doesn’t look like there is any interest in changing that. I got errors very quickly trying to write a script which used private class features like the following :—

    ```js
    class Hyrax {
      #private;

      constructor ( ) {
        this.#private = true;
      }
    }
    ```

    [This code works in every browser we are targeting,](https://caniuse.com/mdn-javascript_classes_private_class_fields) we just can’t ship it. Maybe there is a way around this in newer versions of Rails? But I couldn’t make it work in the 5.2 which we’re running.

- We can’t drop support for Sprockets and just serve JS files directly, because Blacklight and such depend on it, not to mention downstream Hyrax applications. Also…

    > In order to use JavaScript from Rails frameworks like Action Cable, Action Text, and Active Storage, you must be running Rails 7.0+. This was the first version that shipped with ESM compatible builds of these libraries.

    We are not even on Rails 6.0 yet! So we need something which works alongside the existing Rails asset pipeline, not something which replaces it.

The above points were the main impetus behind the explorations in this PR. There are some other things to note :—

- Because Sprockets has fallen out of favour for *application* (but not engine) development, all of the testing frameworks / etc. for developing JavaScript with Sprockets are unmaintained and out‐of‐date. So I wanted a solution with testing / etc. built in, in a way which could be integrated with both CI and our Docker environments.

- As an aside, I agree with @jrochkind that the situation is very confusing and poorly‐documented, and I get the sense that the emphasis with Rails developers themselves is on creating tools which minimize the need for (application/engine) JavaScript, which is kind of the opposite direction from the one the rest of the web is taking (what with Custom Elements and all). Especially considering long‐term maintenance and the amount of churn upgrading a major version of Rails *already* takes, I don’t feel great about leaning too hard on Rails tooling for frontend behaviours, especially considering the extremely very different approaches of Rails 5.0, 6.0, and 7.0 in this regard.

- Whatever solution we choose regarding Hyrax JavaScripts, I don’t want to be doing this again in another five years (or less…). I *don’t seem* to be able to guarantee that working within the Rails ecosystem! But I *can* guarantee it if we just leave the Rails ecosystem behind and hook into something with a little more stability.

@jrochkind I won’t pretend to understand everything about import maps, but it looks to me like they are just a way of specifying import paths in an ergonomic manner. This is already a solved problem in the world of Deno, by including all dependencies in a single `deps.js` file that other files pull from, instead of importing from `https://example.com/mypackage@0.8.7` across 100 files that you will all have to update when `0.9.0` comes out.

In any case, the reason why I chose Deno for this exploration is that one literally *could* just serve the javascripts in `app/scripts/hyrax/` with zero modification and they would function as expected in browsers (which could not necessarily be said of, e.g., Node). Actually *doing* that is problematic for a couple of reasons, and I’m not 100% thrilled if Rails decides to essentially go that route, but transitioning from a Deno system to whatever future system develops should be fairly painless because it is *just* standards‐conformant Ecmascript.

On the gripping hand, I don’t want us to do a bunch of work getting our JavaScripts in order for the Blacklight 7 upgrade and then have to do all of that work over again when we upgrade Rails to 6.0 or otherwise come up with a different JavaScript solution. So we need something which both works today and will work for the foreseeable future, regardless of what happens with our other dependencies. I’m definitely open to other suggestions for solving these problems; this is just the best I’ve been able to manage so far.

**Comment by jrochkind** [comment]
OK, I just want to make sure we're on the same page that that while:

> jsbundler seems to view [working with engines] as infeasible. The recommendation is to use Sprockets (or NPM…).

That's true of jsbundler-rails, but is NOT true of importmaps-rails, which has a documented path for engines. 

The `jsbundler` approach for Rails 7 is supported and is what you use in Rails 7 to use webpacker (or esbuild, or potentially any other js bundler... maybe hypothetically even deno, not sure), but believe it or not, actually NOT the default/standard/"omikase" approach for Rails 7. The importmaps approach is the 'default' approach. And at least potentially/as documented as an engines solution. 

Still, it still may very well be true that this path is the best for dealing with the variation in Rails versions and application practices that you need to deal with -- not trying to challenge that at all! It has gotten to be a very messy environment.  Especially considering that you aren't even on Rails 6.0 yet. :(   I think you could use importmaps-rails with Rails 6.0 (at least it's own dependency requirements allow it), but not Rails 5.2. 

I don't entirely understand what the expectations are in this path for how a hyrax app will bundle both hyrax-distro JS and it's own and possibly other third-party JS. Like, do you use deno for your own local app stuff too?  Is the expectation (happy path? requirement?) that those maintaining individual hyrax-using apps will learn deno and use it for their own assets as well as hyrax-distro assets? I don't entirely understand the role of deno, which is just my own ignorance but others are probably in the same boat.

**Comment by marrus-sh** [comment]
@jrochkind we are on the same page (I think…), but as far as I can tell import maps are not a complete solution in‐and‐of themselves. In our case, we definitely still need Sprockets because some of our dependencies (like Blacklight) use Sprockets to generate the javascripts (which import maps could then feasibly serve…).

> I don't entirely understand what the expectations are in this path for how a hyrax app will bundle both hyrax-distro JS and it's own and possibly other third-party JS.

There are no expectations. This code hooks into `rake assets:precompile` and uses Deno to bundle Hyrax javascripts *only*. The resulting file (now served at `scripts/hyrax.js` and loaded on Hyrax pages) still creates a global object named `Hyrax`, which application scripts can interact with the same as they always have, and there is *no* requirement that application javascripts be bundled or served via the same mechanisms. I would recommend downstream applications continue doing what they have been doing with no changes.

The one caveat is that application scripts which depend on the `Hyrax` object being present should be loaded *after* the Hyrax script, and with a `defer` attribute, to make sure that the Hyrax scripts have time to actually create that object first. This is done by default on Hyrax views for the ordinary `application` script. In a browser, the result looks something like this :—

```html
<!-- This file is generated during assets:precompile. -->
<!-- Creates the `Hyrax` object which may be used by other scripts. -->
<script type="module" src="/scripts/hyrax.js"></script>

<!-- This file can and probably should be generated using the ordinary Rails asset pipeline. -->
<!-- `defer` ensures this loads after any previously declared modules. -->
<script src="/assets/application.js" defer="defer"></script>
```

(See [here](https://github.com/samvera/hyrax/pull/5314/commits/fb653f92db3f305d6cf9ed24642afa010502e07e#diff-f8a8cabe831160bc7a1af37089edaf0fa65723a0a49d9cd23add6e34aa25e4c0R22-R28) for those changes.)

**Comment by jrochkind** [comment]
Thanks @marrus-sh !

> There are no expectations. This code hooks into rake assets:precompile and uses Deno to bundle Hyrax javascripts only. The resulting file (now served at scripts/hyrax.js and loaded on Hyrax pages)

OK, my question as far as expectations -- I don't underestand HOW the "resulting file" is "loaded on hyrax pages".  Via sprockets, bundled into an `application.js? via sprockets?    What if the app doesn't want to use sprockets to bundle it's assets?  

How do the deno-bundled Hyrax javascripts end up served/referenced to be on hyrax pages? Does it allow a consuming application to make it's own choices about how to bundle JS?  Or wait, does it have  a separate <script> tag *just* for hyrax, doesn't bundle hyrax into `application.js` along with local things anymore? 

Sorry if the answers are in the code of this lengthy PR!

**Comment by marrus-sh** [comment]
@jrochkind sorry, i must have missed this comment!!

I’ve written up a more lengthy overview of how this works which will hopefully be more accessible if you want to get into the details: https://ucsb-library.gitlab.io/notes/~kibigo/2022-01-10/deno-rails/

However, to answer your question directly, they get loaded like this :—

```erb
<!-- engine js -->
<%= javascript_include_tag '/scripts/hyrax', type: 'module' %>

<!-- application js -->
<%= javascript_include_tag 'application', defer: '' %>
```

which is to say, your second option, as a separate `<script>` tag from the application javascripts.

Even if we don’t wind up using Deno and use a different bundling mechanism, I think this is the best option going forward, because it gives applications maximum freedom regarding their own assets without affecting ours (and creates a good separation boundary between the two so we aren’t polluting each other’s namespaces).

**Comment by marrus-sh** [comment]
I should add that *most* of Hyrax’s existing JavaScripts are still being bundled into the application through the old mechanism (`//= require "hyrax/hyrax"`); the two can exist side‐by‐side but the hope is that we are inserting less and less into application code directly, and instead existing more in concert.

**Comment by jcoyne** [comment]
> We can’t drop support for Sprockets and just serve JS files directly, because Blacklight and such depend on it

I believe you are mistaken about blacklights dependency on Sprockets.  Blacklight precompiles all it's javascript using node and publishs it as https://www.npmjs.com/package/blacklight-frontend  That said, you could choose to use Sprockets with the blacklight source code, but that is a decision up to the developer.

**Comment by jrochkind** [comment]
@marrus-sh Thanks for the info on javascirpt include tags! I get it.  


> This is true of Blacklight 7, but we’re still on Blacklight 6... but fixing our JavaScript situation is blocking it, and I’m not sure our plate is big enough to do both at the same time.

But these changes you are doing here won't possibly apply to Blacklight 6, right? They'll in fact only apply to Blacklight 8? If this PR lands, you still can't fix your JS situation unless you upgrade first, no?   I feel your pain! But I don't think the situation under BL 6 is relevant to what makes sense for this (or other current) PRs, right?

**Comment by jcoyne** [comment]
@marrus-sh I'm fairly certain that blacklight-frontend 7.0 will work just fine with Blacklight 6.

**Pull request closed without merging**
