### PR TITLE
Prep for 1.0.3 release

### PR DESCRIPTION
**Pull request by dheles**

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@dheles This is the PR you want to resubmit, right? Just checking! I'll take a look at the pending PRs again in a wee bit.

**Comment by dheles** [comment]
@mjgiarlo that is correct. will resubmit shortly. just letting the checks complete, since they have already started. thx

**Comment by mjgiarlo** [comment]
@dheles :ok: :cool:

**Comment by dheles** [comment]
withdrawing in favor of https://github.com/samvera/hyrax/pull/1364

**Pull request closed without merging**
