### PR TITLE
Backport current CircleCI config to 2.0-stable

### PR DESCRIPTION
**Pull request by no-reply**
Since we have switched to CircleCI, we need to backport configuration to maintained branches to keep the build working on them.

@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by cjcolvar** [comment]
Does this need anything else backported (like #3552) or just a rebase?

**Comment by jrgriffiniii** [comment]
I'm finding `chromedriver-helper` installed to the latest release on this branch, so I'm uncertain as to why https://circleci.com/gh/samvera/hyrax/1484 failed with
```
Failure/Error: require 'chromedriver-helper'
LoadError:
  cannot load such file -- chromedriver-helper
```

**Comment by jrgriffiniii** [comment]
Updating `chromedriver-helper` to release 2.1.0 seems to helped solved the problem, but I'm also finding that I needed to lock `capybara-maleficent` to release `0.2` and add `rspec_junit_formatter` in the gemspec.

**Comment by jrgriffiniii** [comment]
This seems to have the tests running now: https://circleci.com/gh/jrgriffiniii/hyrax/147.  I'll issue a PR against this branch.

**Comment by no-reply** [comment]
@cjcolvar asked:

> Is it worth bringing over the ruby 2.6 / 2.5 testing workflow changes?

I don't think that's related to this work.

We do need to get Ruby 2.6 support into this branch sooner or later, but I think we shouldn't leave CI broken waiting for that.

**Pull request merged**
