### PR TITLE
force upgrade of `reform` and `reform-rails`

### PR DESCRIPTION
**Pull request by no-reply**
this is a proposed fix for failing builds caused by
https://github.com/trailblazer/reform/issues/508
and release of `reform` v2.3.1.

@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by seuros** [comment]
Let me know if you have no regression so we can release 0.2.0

**Comment by no-reply** [comment]
@seuros we're all green, here.

**Comment by no-reply** [comment]
rebased this and bumped to the upcoming version numbers. this should go green once a `reform-rails` release happens.

**Comment by seuros** [comment]
@no-reply  we released the versions.

**Pull request merged**
