### PR TITLE
Display recent items according to date uploaded on homepage. #1237

### LINKED ISSUE #1237: Display recent items according to date uploaded
### Descriptive summary

This avoids display of migrated items, which would be sorted according to the system's creation date. Instead we should use date uploaded, which is assigned by Hyrax at the time the original work or file was created.

### Related work

https://github.com/psu-stewardship/scholarsphere/commit/bd4ddffd5

### PR DESCRIPTION
**Pull request by hweng**
Fixes #1237 ; refs #1237

@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by elrayle** [comment]
Can you add a test that shows the sorting happening by upload date?  The other question that came up during a discussion was whether upload date always exists.  And if not, what happens when the upload date is missing?

**Comment by hweng** [comment]
@cjcolvar @elrayle Thank you for your reviewing.   @elrayle, Sorry I missed your questions. 
For tests, I think this address the "sorting happening by upload date", let me know if it looks fine to you:
https://github.com/samvera/hyrax/pull/2813/commits/4f67cdb2dafda987b25db6eb4d0aa636bf0e0819#diff-03664d4a04aba470fb8dff05f83f69dbR14

For question "what happens when the upload date is missing?" It seems to me that the system generate the default value for date_uploaded value anyway.

**Comment by hweng** [comment]
@samvera/hyrax-code-reviewers  
The Travis CI build was failed because of the error:  "SolrWrapper::SolrWrapperError: Unable to download solr from http://www.us.apache.org/dist/lucene/solr/7.4.0/solr-7.4.0.zip.md5":
https://travis-ci.org/samvera/hyrax/jobs/397458791

Looking into http://www.us.apache.org/dist/lucene/solr/7.4.0/,  "solr-7.4.0.zip.md5" is not found in this directory.  Is the URL out-of-dated?

**Comment by RudyOnRails** [comment]
@hweng, there was a fix in solr_wrapper to combat the apache md5 publishing issue. solr_wrapper has been relaxed in the gemsepc and merged into master, so if you rebase onto master or cherry-pick https://github.com/samvera/hyrax/commit/1de3bbcde5ce2030b24486afd1d406ef7956177c, you'll be good to go.

**Pull request merged**
