### PR TITLE
Marks `spec/models/concerns/hyrax/solr_document/ordered_members_spec.rb` as ActiveFedora-only.

### PR DESCRIPTION
**Pull request by bwatson78**
### Fixes

Fixes `spec/models/concerns/hyrax/solr_document/ordered_members_spec.rb`.

### Summary

Marks `spec/models/concerns/hyrax/solr_document/ordered_members_spec.rb` as ActiveFedora-only.

### Type of change (for release notes)

- `notes-valkyrie` Valkyrie Progress

@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by dlpierce** [comment]
Won't we need ordered_targets_ssim to be available for MemberPresenterFactory to work? I think we still need that in valkyrie.

**Comment by bwatson78** [comment]
Looking now...

**Comment by bwatson78** [comment]
What I'm seeing if that we have a `PcdmMemberPresenterFactory` for Valkyrie objects. That's being switched to here: https://github.com/samvera/hyrax/blob/f2fed7aed2b6ba2168668b95a9e65ea794fb4079/app/presenters/hyrax/work_show_presenter.rb#L304. I've also checked to see where `ordered_member_ids` is being used, and everywhere I'm seeing it is in the Actor Stack(`Hyrax::Actors::ApplyOrderActor`) or a ternary is in place to not use it in Valkyrie (`Hyrax::IiifManifestPresenter` L#97 and `app/views/hyrax/base/_file_manager_members.html.erb` L#8 .

**Comment by bwatson78** [comment]
@dlpierce ^ What do you think?

**Review by dlpierce — APPROVED** [review]
Okay, thanks for the investigation!

**Pull request merged**
