### PR TITLE
Re-sort locale files and update missing translations for consistency

### PR DESCRIPTION
**Pull request by mjgiarlo**
Also, expand reach of `i18n_sorter` task to sort locale files in all their locations

Refs #2274. Follows work I asked @hweng about in comments on that PR, not realizing our English files were out of sort order.

@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by jcoyne** [comment]
Blocked by #2288 (because there's a substantial change to the translations in that PR)

**Comment by jcoyne** [comment]
@mjgiarlo there are now conflicts in hyrax.en.yml. Can you resolve them?

**Comment by mjgiarlo** [comment]
@jcoyne will do

**Comment by mjgiarlo** [comment]
@jcoyne done.

**Pull request merged**
