### PR TITLE
Fix tests that do database checks without visual synch

### LINKED ISSUE #2642: Capybara 2.18.0 causes test failures
### Descriptive summary

Capybara recently updated its version from 2.17.0 to 2.18.0.  This caused 3 tests to fail in Travis for all PRs.  There needs to be an exploration for why the tests fail and a fix for those tests.  This will allow us to remove the temporary pin of capybara to < 2.18.0.

### Rationale

We do not want to pin gems to a specific version if we can avoid it.

### Expected behavior

All tests should pass with capybara 2.18.0

### Actual behavior

3 tests fail with capybara 2.18.0

```
rspec ./spec/features/browse_dashboard_works_spec.rb:49 # Browse Dashboard allows me to delete works in upload_sets
rspec ./spec/features/batch_edit_spec.rb:66 # batch deleting destroys the selected works
rspec ./spec/features/ownership_transfer_spec.rb:41 # Transferring work ownership: When I request a work transfer: To someone else If the new owner accepts it I should see it was accepted
```

### Steps to reproduce the behavior

```
$ bundle update capybara
$ bundle show capybara
capybara-2.18.0
```
run each of the failing tests listed under Actual behavior and see that they pass.

### Related work

PR #2643 temporary pin of capybara to < 2.18.0

### PR DESCRIPTION
**Pull request by twalpole**
Fixes #2642

This fixes poorly written tests that had issues with Capybara 2.18.0 due to it returning faster than 2.17.x when using `accept_confirm`

### CODE REVIEW

**Comment by jenlindner** [comment]
The transfer request spec is still failing with the visual confirmation check (the other test is failing for content mismatch). I'm looking at this locally now.

**Comment by twalpole** [comment]
iCLA filed

**Comment by twalpole** [comment]
The first error appears to be different than this PR was intended to fix, the second is because I added the expectation to a shared method.  Will fix.

**Comment by twalpole** [comment]
@jenlindner @jcoyne Ok - this should fix the tests now, although it failed due to Travis timing out the build.  Nothing has changed that should cause the tests to take that much longer, so I assume it was a slow travis instance.  Could someone just restart the build that timed out?

**Comment by jenlindner** [comment]
@twalpole restarted

**Comment by twalpole** [comment]
Exceeded maximum time again, I have no clue what's going on with Travis.

**Comment by twalpole** [comment]
@RudyOnRails The startup time is longer (but that's really negligible when you have a 30+ minute test suite).  The upside is that the total time tends not to vary nearly as much.  The container environment was varying from 30 - 50 minutes for total test time.  Whether that is purely because the  virtual machine has more resources, or because it reduces the effects of other containers on the one running the tests isn't 100% clear.

**Comment by twalpole** [comment]
@cjcolvar I filed the CLA a week ago -- is there anything else blocking this?

**Pull request merged**
