### PR TITLE
Backport of after_destroy to before_destroy fix

### LINKED ISSUE #762: Ldp::Gone error after deleting a work or files from a work
When I delete a work or file (delete link in dropdown, or delete button), I get an Ldp::Gone error.
Hyrax master branch

Expected behavior
After deleting a work, it should redirect to the dashboard
After deleting a file from a work, it should redirect to the work

Actual behavior
Ldp::Gone error

Steps to reproduce the behavior

1. Create a new work
1. Delete the work (or a file in the work)

Related work
Same [issue](https://github.com/projecthydra-labs/hyku/issues/940) in Hybox

### PR DESCRIPTION
**Pull request by kdid**
Backport of #797 

Fixes #762 on Hyrax 1.x

@projecthydra-labs/hyrax-code-reviewers

### CODE REVIEW

**Comment by jcoyne** [comment]
@kdid it looks like you're going to have to adjust the feature test you ported over, because those routes don't exist in version 1.0

**Comment by kdid** [comment]
@jcoyne - I updated the route in the feature test.  I'm unclear about the `I18n::MissingTranslationData` errors in the tests - they don't seem related to these code changes.

**Comment by jcoyne** [comment]
@kdid yeah, that's pretty confusing. I'll have a look at this branch and see if I can figure it out.  Thanks for your work.

**Comment by kdid** [comment]
@jcoyne - thanks. We are seeing the same errors on the 1-0-1-stable branch as well, when we run the tests locally.

**Comment by jcoyne** [comment]
@kdid Okay, I think the problem was caused by an update to the i18n gem, and the fix is in #1178, so once that is merged, you can rebase this change and hopefully it'll go green.

**Pull request merged**
