### PR TITLE
Improved /downloads request for status 401 with no permissions.

### LINKED ISSUE #1410: /downloads request you don't have permission for gives you the default icon
If browser requests a /downloads link that the user-agent isn't auth'd to see (say, a non-public image when you are not logged in), instead of a 403 the default icon is delivered. 

One problem with this is if you are setting caching headers, say far-future caching headers as probably makes sense for image assets, the user-agent (or any intermediate caches) now caches that default icon for that URL, when that is not the right thing to cache far-future for that URL. Now you've got cache issues.

### PR DESCRIPTION
**Pull request by lsitu**
Fixes #1410
Improved /downloads request with status 401 when user has no permission.

Currently /downloads request gives you the default icon if you don't have permission for it. The change in this PR is to gives status 401 with default text content.

@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by cjcolvar** [comment]
Seeing as this is a functionality change I wanted to trace the origin of the original functionality and tracked it down to this issue: https://github.com/samvera/sufia/issues/2394
I don't have time right now to fully review this change but if others are doing so please see this issue.

**Comment by cjcolvar** [comment]
@lsitu I tested this out and found that the old behavior where broken icons are displayed appears again in your branch.  So this PR fixes one thing and regresses another.  Maybe this PR needs to fix the underlying problem of https://github.com/samvera/sufia/issues/2394 by not showing filesets that the user doesn't have access to?  It looks like there is a version of this change in scholarsphere that might be able to be adapted for hyrax: https://github.com/psu-stewardship/scholarsphere/issues/431.

**Comment by lsitu** [comment]
@cjcolvar Thank you very much for the review and your suggestions.

**Comment by lsitu** [comment]
@cjcolvar Will resolve ticket https://github.com/samvera/hyrax/issues/2796 (Only show files users have permission to see) fix the problem you see?

**Comment by cjcolvar** [comment]
I was hoping that it would but I'm not so sure now.  I'm waiting to see how that ticket shapes up with respect to backwards compatibility and if the old behavior needs to stay supported.

This PR has been open for a while now.  Is this something that you need merged quickly or is it okay for it to sit until #2796 is finished?

**Comment by lsitu** [comment]
@cjcolvar No, I think we can wait until https://github.com/samvera/hyrax/issues/2796. 
I was thing about a similar solution as ticket https://github.com/samvera/hyrax/issues/2796 not to show the private files in the public work that the users don't have access. How about I push a commit here or in https://github.com/samvera/hyrax/issues/2796 so that you can test it out?

**Comment by lsitu** [comment]
@cjcolvar I've added the commit https://github.com/samvera/hyrax/pull/2641/commits/5ab841c3834bcd37818fc4a98797ff2cd35109bd (Only show files that the user have permission to see.) above not to display those files that users don't have permission to see. Let me know if this could solve the problem you see or not. Thanks.

**Comment by lsitu** [comment]
@cjcolvar I don't think resolving ticket #2796 will fix the broken links issue you see with the implementation. I've updated the PR for it  but the internal test app need rebuild for the default unauthorized image added. Please let me know if you still see any issue with it.

**Comment by cjcolvar** [comment]
@lsitu I'll take a look at this again tomorrow.

**Comment by no-reply** [comment]
Does this require a rerun of the asset generator to work on an existing app?

**Comment by lsitu** [comment]
@no-reply No, I think copy & paste the unauthorized.png file to app/assets/images/unauthorized.png on an existing app should work.

**Comment by cjcolvar** [comment]
What about checking for the existence of the image file and if present then send it like you have but fallback to the old behavior if not present?  This way it is backwards compatible and one could opt-in by copying the file into place.  Then at a major release we can require copying the file into place.

**Comment by jcoyne** [comment]
👍  on the 401 status change. This is the right thing to do.

I share @no-reply's concern, that this has some upgrade requirements, so either:
  1. Check for the files existence, and if it's not found, give a deprecation warning and do the old behavior.
  1. Create an initializer that copies the file in place if it didn't exist before.
  1. Something else?

**Pull request merged**
