### PR TITLE
WIP Postgresql?

### PR DESCRIPTION
**Pull request by jeremyf**
Stay tuned for a meaningful PR message and squashed commits.

### CODE REVIEW

**Comment by jeremyf** [comment]
I am stuck on fixing the broken PR. On this branch, I have one local spec failing:

```console
$ rspec /Users/jfriesen/git/hyrax/spec/features/create_child_work_spec.rb:23

  1) Creating a new child Work creates the child work
     Failure/Error: expect(page.status_code).to match(%r{^3}), "The response code indicates that we failed to create a generic work"
       The response code indicates that we failed to create a generic work
     # ./spec/features/create_child_work_spec.rb:31:in `block (2 levels) in <top (required)>'
```

What I have found is in [AddToWorkActor](https://github.com/samvera/hyrax/blob/adding-postgresql-as-database-to-circle-ci/app/actors/hyrax/actors/add_to_work_actor.rb#L23), this method returns false (which in turn adds the error and fails the save for the controller action):

```ruby
def can_edit_both_works?(env, work)
  env.current_ability.can?(:edit, work) && env.current_ability.can?(:edit, env.curation_concern)
end
```

When I checked both of them, the work (e.g. the parent work) could be edited but the newly deposited curation concern (e.g. the child work) could not be edited:

```ruby
env.current_ability.can?(:edit, work)
=> true
env.current_ability.can?(:edit, env.curation_concern)
=> false
```

A little further digging, and the solr document for the `env.curation_concern` does not have the appropriate attributes.

## Helping Out

I would be available to schedule some remote pairing, as my environment is up and running.

If you are interested in testing locally, you need to use Postgres as the database for your internal test application. I previously had Postgres running, but used the following to rebuild my `.internal_test_app`:

```console
$ ENGINE_CART_RAILS_OPTIONS="--database=postgresql --skip-git --skip-bundle --skip-listen --skip-spring --skip-keeps --skip-test --skip-bootsnap" rake engine_cart:regenerate
```

**Comment by straleyb** [comment]
Im pulling this down and firing up a new test app now. Ill poke into that failing test and see if I can figure anything out. Ill make sure to check the attributes of the child work. I wonder if the depositor isn't being set properly or something like that.

**Comment by straleyb** [comment]
@jeremyf So I tried to regenerate my test app but got PG::ConnectionBad.

What was the command that you used to fire up PG properly?

**Comment by straleyb** [comment]
So for postgres, you will have to make a server called `internal_development` which I think can be done using the command `initdb -D /usr/local/pgsql/internal_development` then `pg_ctl -D /usr/local/pgsql/internal_development -l logfile start` assuming you have postgres installed.

**Comment by jeremyf** [comment]
@straleyb I'm taking a family sick day today, so I'm not fully available. I got `postgresql` running via `brew`.

**Comment by straleyb** [comment]
All good. Take it easy and rest up! I'll continue to update my steps here.

**Comment by cjcolvar** [comment]
Bump to keep this alive.

**Comment by cjcolvar** [comment]
Bump again to keep this alive.

**Comment by cjcolvar** [comment]
Bumping another time.

**Comment by mjgiarlo** [comment]
@jeremyf might you have time to take a look in the coming weeks?

**Comment by jeremyf** [comment]
I'll begin giving it a go.

**Comment by jeremyf** [comment]
Not looking forward to writing the atomic commits for this PR (it's really a hack job)

**Comment by jeremyf** [comment]
I closed this in favor of another consolidated PR

**Pull request closed without merging**
